### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Frouk3** [notgoodusename/OsirisAndExtra#10]
https://github.com/notgoodusename/OsirisAndExtra/blob/19d98791fe4e43d7adb30689c7e5839c9362c600/Osiris/Hacks/AntiAim.cpp#L296

I guess you must to write `#include "../Memory.h"`

**Comment by ohkriss** [comment]
This doesn't fix anything, I guess your intellisense is slow as to why your have an error on that line. Memory.h is included in Entity.h as well.

**Comment by Frouk3** [comment]
> This doesn't fix anything, I guess your intellisense is slow as to why your have an error on that line. Memory.h is included in Entity.h as well.

Well in original Osiris where i was doing custom build i've had an error like "namespace *memory not defined"
I'm just an C++ beginner so my errors are stupid
