### ISSUE TITLE
legitbot desync animation looks broken

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#102]
doesn't shown correctly on lby

**Comment by notgoodusename** [comment]
It works fine idk what u mean

**Comment by Rrhyast** [comment]
Uploading 2022-04-24 08-41-20.mp4…

**Comment by Rrhyast** [comment]
https://user-images.githubusercontent.com/62977195/164999154-5d1e8216-0eeb-4e03-86a0-05da7b12bc52.mp4

**Comment by propane** [comment]
the flickering?

**Comment by Rrhyast** [comment]
> the flickering?

YES
