### ISSUE TITLE
NO ANTI-UNTRUSTED???!!!

### ISSUE THREAD

**Issue by Rrhyast** [notgoodusename/OsirisAndExtra#103]
man wtf
![csgo_IJ22Xvr8ck](https://user-images.githubusercontent.com/62977195/165006260-155df208-1427-4e32-8e10-531546970cbc.png)

**Comment by XJN2** [comment]
why r u even cheating on a prime acc

**Comment by Rrhyast** [comment]
> why r u even cheating on a prime acc

its fake prime ahahahaha

**Comment by notgoodusename** [comment]
> man wtf ![csgo_IJ22Xvr8ck](https://user-images.githubusercontent.com/62977195/165006260-155df208-1427-4e32-8e10-531546970cbc.png)

Dont rage on basically any gamemode that isnt mm/wingman/danger zone, it gets you an easy untrusted ban
also check [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/479286-causes-untrusted-bans.html)

**Comment by Rrhyast** [comment]
> > man wtf ![csgo_IJ22Xvr8ck](https://user-images.githubusercontent.com/62977195/165006260-155df208-1427-4e32-8e10-531546970cbc.png)
> 
> Dont rage on basically any gamemode that isnt mm/wingman/danger zone, it gets you an easy untrusted ban also check [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/479286-causes-untrusted-bans.html)

That's right

**Comment by gr1ndy** [comment]
> man wtf ![csgo_IJ22Xvr8ck](https://user-images.githubusercontent.com/62977195/165006260-155df208-1427-4e32-8e10-531546970cbc.png)

LMAO
