### ISSUE TITLE
shot delay + accuracy boost 

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#104]
since hitchance doesn't guarantee u hit successfully, It might help reducing shot missess

**Comment by voidzer0-development** [comment]
Accuracy boost is just another name for backtrack

**Comment by propane** [comment]
'Accuracy boost' in gamesense.pub is just backtracking. But in some other cheats there is an accuracy boost which works with the hitchance which just changes the percent of seeds the hitchance will check... lower accuracy percent meaning ex. only cast 50 rays to check hitchance instead of 255

**Comment by voidzer0-development** [comment]
> 'Accuracy boost' in gamesense.pub is just backtracking. But in some other cheats there is an accuracy boost which works with the hitchance which just changes the percent of seeds the hitchance will check... lower accuracy percent meaning ex. only cast 50 rays to check hitchance instead of 255

Well yeah, I wouldnt call that accuracy boost though since you just lower it, a better description would be FPS boost xd
Anyways a description that actually explains the feature instead of something vague with differing interpretations would greatly help the developers
