### ISSUE TITLE
Better font + Stroke + Bold

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#106]
I don't know what exactly the default osiris font name is, but the font is horrible, open sans font is great. it's more viable and visible than other fonts. https://fonts.google.com/specimen/Open+Sans

**Comment by gr1ndy** [comment]
you are aware that u can change the esp font to whatever u like, right?

**Comment by Rrhyast** [comment]
> you are aware that u can change the esp font to whatever u like, right?

doesn't matter when it has same setting as default font. it just make it worse.
