### ISSUE TITLE
[ Suggestion ] Add a button to turn on and off the resolver 

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#107]
why am i saying this? Because i can kill this cheat without resolver with the same cheat.

**Comment by voidzer0-development** [comment]
The resolver doesnt really do any real 'resolving' yet only lagcompensating and animfixing

**Comment by notgoodusename** [comment]
I havent found a somewhat consistent method of resolving

**Comment by cristyanul** [comment]
> I havent found a somewhat consistent method of resolving

It doesn't have to be that consistent, it's decent just to calculate moving angles by `ANIMATION_LAYER_MOVEMENT_MOVE`
You could also try using `ANIMATION_LAYER_ADJUST` and `ANIMATION_LAYER_LEAN` or just safepoint if it misses.

**Comment by propane** [comment]
> > I havent found a somewhat consistent method of resolving
> 
> It doesn't have to be that consistent, it's decent just to calculate moving angles by `ANIMATION_LAYER_MOVEMENT_MOVE` You could also try using `ANIMATION_LAYER_ADJUST` and `ANIMATION_LAYER_LEAN` or just safepoint if it misses. [UC Link](https://www.unknowncheats.me/forum/2916159-post19.html)

he doesnt have multiple desync matrixes setup yet, so he cant safepoint...
