### ISSUE TITLE
Suggestion: import matchmaking fakeduck

### ISSUE THREAD

**Issue by hedgyx** [notgoodusename/OsirisAndExtra#110]
KittenPopo made an interesting post about how you can fakeduck in matchmaking at https://www.unknowncheats.me/forum/counterstrike-global-offensive/410064-fakeduck-matchmaking.html

the source code on the site is 

	if (FakeDuck.Enabled()) {
		bSendPacket = false;
		static bool down = false;
 
		int mod = cmd->tickcount % 14;
		switch (mod) {
			case 0:
			down = true; break;
			case 6:
			bSendPacket = true; break;
			case 7:
			down = false; break;
		}
 
		// Prevent shots from not being registered on server
		if (chokedTicks > 8)
			cmd->buttons &= ~IN_ATTACK;
 
		if (down)
			cmd->buttons |= IN_DUCK;
		else
			cmd->buttons &= ~IN_DUCK;
 
	}

is there a way to somehow import this into betterosiris?

**Comment by cristyanul** [comment]
I'll try it right now

**Comment by hedgyx** [comment]
> I think it works: [Test image](https://i.imgur.com/b0QUBYo.png)

does it actually work in matchmaking? so far i only tested it on local server and it looks just like normal fakeduck to me

**Comment by cristyanul** [comment]
> > I think it works: [Test image](https://i.imgur.com/b0QUBYo.png)
> 
> does it actually work in matchmaking? so far i only tested it on local server and it looks just like normal fakeduck to me

[Test image2](https://i.imgur.com/7oqSWS2.png)

**Comment by dapaster** [comment]
@notgoodusename check this out, its working for me

**Comment by dapaster** [comment]
its working but i got this
![image](https://user-images.githubusercontent.com/60472098/165999562-c58fa0d7-3b55-4f8f-aea5-3b10890fd26f.png)

**Comment by cristyanul** [comment]
If you’re using tickbase, don’t enable it during freeze time. That causes that issue
