### ISSUE TITLE
Disconnected by VAC: You cannot play on secure servers

### ISSUE THREAD

**Issue by Exploriant** [notgoodusename/OsirisAndExtra#112]
Sometimes I randomly get the message "Disconnected by VAC: You cannot play on secure servers" when playing and I have to verify game files. How do I fix this from stopping

**Comment by cristyanul** [comment]
Don't play non-competitive game modes with >39 delta, look up aimstep if you want more info

**Comment by Exploriant** [comment]
> Don't play non-competitive game modes with >39 delta, look up aimstep if you want more info

Could this be because i have 255 delta? Idk what delta is so i just kept it at that
