### ISSUE TITLE
Port double tap from old project

### ISSUE THREAD

**Issue by M1sp** [notgoodusename/OsirisAndExtra#113]
You added a doubletap in the old other Osiris project, would be great to see that or a recode in this one. Cheat really does need a doubletap.

**Comment by cristyanul** [comment]
If you need it that much (like I did), just merge with tickbase branch or use my clone. It has mm fakeduck and tickbase built-in.
It's not the best tickbase ever, but @notgoodusename will recode it, as you can see in the TODO list.
