### ISSUE TITLE
Suggestion: grenade lineups helper

### ISSUE THREAD

**Issue by Exploriant** [notgoodusename/OsirisAndExtra#114]
You can record a lineup and it will recreate the lineup perfectly everytime. Or you can make lineups with a press of an button and recreate by standing on the location and throwing manually

**Comment by voidzer0-development** [comment]
Duplicatie
https://github.com/notgoodusename/OsirisAndExtra/issues/74
https://github.com/notgoodusename/OsirisAndExtra/issues/76
