### ISSUE TITLE
[Issue] Assertion Failed

### ISSUE THREAD

**Issue by dapaster** [notgoodusename/OsirisAndExtra#115]
randomly crash
![image](https://user-images.githubusercontent.com/60472098/166480855-8667f36c-72f6-4eb8-9b98-17b2588a4a97.png)

**Comment by dapaster** [comment]
and again
![image](https://user-images.githubusercontent.com/60472098/166488669-48625d26-43ef-48e7-9599-4fe1fe360b4e.png)

**Comment by Patrixsin** [comment]
verify ur game files
