### ISSUE TITLE
Aimstep

### ISSUE THREAD

**Issue by Rrhyast** [notgoodusename/OsirisAndExtra#116]
without it u can speedrun %any overwatch ban.

**Comment by Patrixsin** [comment]
Aimstep is exactly max angle delta

**Comment by voidzer0-development** [comment]
High aimstep should not cause untrusted bans only vac kicks. 
Try setting max angle delta to 29, works for me.

**Comment by Patrixsin** [comment]
> > Aimstep is exactly max angle delta also overwatch doesnt work and bans that are for cheating are untrusted due to high aimstep
> 
> nice opinion but one small issue, my research and result says another thing: ![firefox_WTXqJfGxt2](https://user-images.githubusercontent.com/62977195/166567913-d82155a5-d87f-4d19-9768-026789226ca8.png) ![firefox_16n6OrCbk7](https://user-images.githubusercontent.com/62977195/166567945-b16edf5e-f140-408f-9089-83d4ecc76265.png) ![firefox_7Ee26PH0wc](https://user-images.githubusercontent.com/62977195/166567958-75ef1a71-5465-446e-badb-40771f76e83d.png) ![firefox_lRXXcVB6gP](https://user-images.githubusercontent.com/62977195/166567999-bf441a22-2f77-4e89-be64-d3f1e460ae0e.png) ![firefox_cfIdwhhNwL](https://user-images.githubusercontent.com/62977195/166568027-83002630-243a-4ed2-a6ce-20b1d585d24b.png)

LMAOOOO
