### ISSUE TITLE
HUGE FPS DROP 

### ISSUE THREAD

**Issue by Rrhyast** [notgoodusename/OsirisAndExtra#128]
IDK what exactly it is but my fps drop from 120 - 150 to 40 - 60, tried other cheats or without cheat, not a single problem, but i care about this one.

**Comment by pepsiis** [comment]
Same

**Comment by Exploriant** [comment]
same

**Comment by voidzer0-development** [comment]
https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling?view=vs-2022

Post the result here
