### ISSUE TITLE
[Feature] Anti-Recoil + Code

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#135]
I don't know how to merge, but here is the code from [dainsleif](https://github.com/pseuxidal/Dainsleif/blob/bca741359d5251833908b4877f94d6c383fee59b/Dainsleif/Hacks/AntiRecoil.cpp) it works very well.

**Comment by Navoichyk** [comment]
> I don't know how to merge, but here is the code from [dainsleif](https://github.com/pseuxidal/Dainsleif/blob/bca741359d5251833908b4877f94d6c383fee59b/Dainsleif/Hacks/AntiRecoil.cpp) it works very well.

how do i add this lol?
