### ISSUE TITLE
Where can i find class Player?

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#136]
please tell me i wanna add armor bar

**Comment by Metaphysical1** [comment]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/SDK/PlayerResource.h#L25

**Comment by Patrixsin** [comment]
> https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/SDK/PlayerResource.h#L25

its ain't player class. Player class is entity.h afaik

**Comment by Metaphysical1** [comment]
> Better is use: https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/SDK/Entity.h#L602 i guess


I guess CSPlayerResource gets updated even if the player is dormant
