### ISSUE TITLE
I havent modified the config.cpp at all and i get this error

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#143]
![image](https://user-images.githubusercontent.com/86556266/170833792-455c8c91-9d32-444f-b32e-004bfcc76cb7.png)

**Comment by Patrixsin** [comment]
prop fake error. if it compiles normally with this error then fake

**Comment by alerion921** [comment]
I had that error when i incompletly modified one of the structs inside visuals, if you go over the latest edits you did you might find where the error is, also check inside compiler warnings 😁
