### ISSUE TITLE
suggestion: custom weapon models

### ISSUE THREAD

**Issue by Exploriant** [notgoodusename/OsirisAndExtra#145]
yes

**Comment by Rafael2030** [comment]
use migi

**Comment by Exploriant** [comment]
> use migi

Isn't that private servers only

**Comment by Patrixsin** [comment]
> > use migi
> 
> Isn't that private servers only

use migi + sv_pure

**Comment by Exploriant** [comment]
> 

What does that do

**Comment by Patrixsin** [comment]
> > 
> 
> What does that do

sv_pure bypass allows u to use custom models/materials/sounds without kicking you from valve servers

**Comment by Exploriant** [comment]
Is there an tutorial

**Comment by Patrixsin** [comment]
https://www.youtube.com/watch?v=oLWlMRPts5g

**Comment by Exploriant** [comment]
> https://www.youtube.com/watch?v=oLWlMRPts5g

How do I inject cheat and stay undetected?

**Comment by Patrixsin** [comment]
> > https://www.youtube.com/watch?v=oLWlMRPts5g
> 
> How do I inject cheat and stay undetected?

like normal

**Comment by Exploriant** [comment]
> > > https://www.youtube.com/watch?v=oLWlMRPts5g
> > 
> > 
> > How do I inject cheat and stay undetected?
> 
> like normal, run csgo with migi and inject like always

yeah no half of the models dont work so im just gonna leave the suggestion
