### ISSUE TITLE
suggestion: custom weapon models and night time lightning

### ISSUE THREAD

**Issue by Exploriant** [notgoodusename/OsirisAndExtra#148]

**Comment by Patrixsin** [comment]
For custom weapon models use migi. For use brightness Slider and world color pickers to simulate night mode

**Comment by Exploriant** [comment]
> For custom weapon models use migi. To simulate nightmode use brightness slider and world color pickers

Migi doesn't work for me and world color has weird textures

**Comment by Patrixsin** [comment]
Do u use Migi with VGUI style one?

**Comment by Exploriant** [comment]
> Do u use Migi with VGUI style one?

Idk, i tried it out yesterday and it kept om crashing when starting game. Also after injecting the dll it crashed

**Comment by Patrixsin** [comment]
seems like ur models may be broken, i had one time this issue with broken model
