### ISSUE TITLE
Can anyone post their rage config here

### ISSUE THREAD

**Issue by GetRektLOL** [notgoodusename/OsirisAndExtra#15]
I used legit hacks for a long time, but i am kinda new to this rage stuff, can anyone please post their best config here. I tried making my own but i always messed it up somehow and couldnt find out what did it. Thanks

**Comment by GetRektLOL** [comment]
guys please post

**Comment by notgoodusename** [comment]
[here](https://mega.nz/file/vLwSQJTa#iVXi3hjG7q2s19TZSac3ob0sFQnnz6tACzdH7_LIHpA)

**Comment by GetRektLOL** [comment]
thanks man, i appreciate it
