### ISSUE TITLE
suggestion: movement tab. 

### ISSUE THREAD

**Issue by Exploriant** [notgoodusename/OsirisAndExtra#152]
longjump, edgebug, jumpbug...

**Comment by Rrhyast** [comment]
> longjump, edgebug, jumpbug...

:/

**Comment by Exploriant** [comment]
> > longjump, edgebug, jumpbug...
> 
> :/

What

**Comment by Patrixsin** [comment]
https://github.com/notgoodusename/OsirisAndExtra/projects/1#card-79733337

**Comment by Rafael2030** [comment]
#153

**Comment by Exploriant** [comment]
> #153

Can you also paste in a dot as a recoil crosshair and your own as sniper/no scope crosshair?

**Comment by Navoichyk** [comment]
> 

This would be very nice. IMO the recoil/noscope crosshair is too clunky.

**Comment by 2lag** [comment]
> longjump, edgebug, jumpbug...

i already added lj, mj, ps to mine. its really not that hard..

heres the source for minijump on edgejump, you can modify it to do longjumps, and theres publicly available pixel surf code so im not going to even bother with that.

`void Misc::minijump(UserCmd* cmd) noexcept
{
    static int minijump_tick = 0;
    static bool minijumpbool = false;

    if (config->misc.minijump && config->misc.minijumpkey.isActive())
    {
        if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
        {
            cmd->buttons |= UserCmd::IN_JUMP;
            minijumpbool = true;
            minijump_tick = memory->globalVars->tickCount + 1;
        }

        if (minijumpbool && memory->globalVars->tickCount < minijump_tick)
        {

            if (config->misc.fastDuck)//changed from just ducking
                cmd->buttons &= ~UserCmd::IN_BULLRUSH;
            cmd->buttons |= UserCmd::IN_DUCK;
            interfaces->engine->clientCmdUnrestricted("-forward");
            cmd->buttons &= ~UserCmd::IN_BACK;
            minijumpbool = false;
        }
    }
}`

**Comment by kolnbfioNAFIOABNSFION8902AFASF** [comment]
> > longjump, edgebug, jumpbug...
> 
> i already added lj, mj, ps to mine. its really not that hard..
> 
> heres the source for minijump on edgejump, you can modify it to do longjumps, and theres publicly available pixel surf code so im not going to even bother with that.
> 
> ```
> void Misc::minijump(UserCmd* cmd) noexcept
> {
>     static int minijump_tick = 0;
>     static bool minijumpbool = false;
>     if (config->misc.minijump && config->misc.minijumpkey.isActive())
>     {
>         if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
>         {
>             cmd->buttons |= UserCmd::IN_JUMP;
>             minijumpbool = true;
>             minijump_tick = memory->globalVars->tickCount + 1;
>         }
> 
>         if (minijumpbool && memory->globalVars->tickCount < minijump_tick)
>         {
>             if (config->misc.fastDuck)//changed from just ducking
>                 cmd->buttons &= ~UserCmd::IN_BULLRUSH;
>             cmd->buttons |= UserCmd::IN_DUCK;
>             interfaces->engine->clientCmdUnrestricted("-forward");
>             cmd->buttons &= ~UserCmd::IN_BACK;
>             minijumpbool = false;
>         }
>     }
> }
> ```

what have u added whats ur discord?

**Comment by kolnbfioNAFIOABNSFION8902AFASF** [comment]
> > longjump, edgebug, jumpbug...
> 
> i already added lj, mj, ps to mine. its really not that hard..
> 
> heres the source for minijump on edgejump, you can modify it to do longjumps, and theres publicly available pixel surf code so im not going to even bother with that.
> 
> ```
> void Misc::minijump(UserCmd* cmd) noexcept
> {
>     static int minijump_tick = 0;
>     static bool minijumpbool = false;
>     if (config->misc.minijump && config->misc.minijumpkey.isActive())
>     {
>         if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
>         {
>             cmd->buttons |= UserCmd::IN_JUMP;
>             minijumpbool = true;
>             minijump_tick = memory->globalVars->tickCount + 1;
>         }
> 
>         if (minijumpbool && memory->globalVars->tickCount < minijump_tick)
>         {
>             if (config->misc.fastDuck)//changed from just ducking
>                 cmd->buttons &= ~UserCmd::IN_BULLRUSH;
>             cmd->buttons |= UserCmd::IN_DUCK;
>             interfaces->engine->clientCmdUnrestricted("-forward");
>             cmd->buttons &= ~UserCmd::IN_BACK;
>             minijumpbool = false;
>         }
>     }
> }
> ```

@2lag how much u want for ur src

**Comment by 2lag** [comment]
@kolnbfioNAFIOABNSFION8902AFASF what part of the source are you looking for? just movement features?

**Comment by kolnbfioNAFIOABNSFION8902AFASF** [comment]
> @kolnbfioNAFIOABNSFION8902AFASF what part of the source are you looking for? just movement features?

yessir

**Comment by 2lag** [comment]
contact me on discord and ill be able to help you out. i can show you everything. day#0007
