### ISSUE TITLE
Problem with hooking CalcViewBob

### ISSUE THREAD

**Issue by worse-666** [notgoodusename/OsirisAndExtra#154]
I saw [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/392405-disabling-view-bob.html) on uc, and I found the pattern [here](https://github.com/KittenPopo/csgo-offsets/blob/master/function_signatures.h#L44).
How do I hook  CalcViewBob?

**Comment by alerion921** [comment]
Cant you just add it to memory.cpp with CLIENT_DLL.

Do you need to hook it, just wondering?

**Comment by worse-666** [comment]
I mean how to call original, and how to find the index

**Comment by notgoodusename** [comment]
> I mean how to call original, and how to find the index

Look into how most of this [hooks ](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hooks.h#L42-L46)are used

**Comment by worse-666** [comment]
> > I mean how to call original, and how to find the index
> 
> Look into how most of this [hooks ](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hooks.h#L42-L46)are used

Thank you, it works very well!
![image](https://user-images.githubusercontent.com/30064486/172095189-4be5b68f-718a-4983-8cf4-305f96d3f7b9.png)

**Comment by alerion921** [comment]
> > > I mean how to call original, and how to find the index
> > 
> > 
> > Look into how most of this [hooks ](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hooks.h#L42-L46)are used
> 
> Thank you, it works very well! ![image](https://user-images.githubusercontent.com/30064486/172095189-4be5b68f-718a-4983-8cf4-305f96d3f7b9.png) https://imgur.com/pC4MBkn

do you have the hooking index?

**Comment by worse-666** [comment]
You don't need an index, it's MinHook.

**Comment by alerion921** [comment]
> You don't need an index, it's MinHook.

Thanks!
