### ISSUE TITLE
Crash after loading configs… [Watch the video first]

### ISSUE THREAD

**Issue by Rrhyast** [notgoodusename/OsirisAndExtra#157]
https://files.catbox.moe/sdh9th.mp4

**Comment by alerion921** [comment]
> https://files.catbox.moe/sdh9th.mp4

Did u test loading the config after the crash when nothing is enabled?

**Comment by Exploriant** [comment]
> https://files.catbox.moe/sdh9th.mp4

That's because ur Ingame

**Comment by Patrixsin** [comment]
> > https://files.catbox.moe/sdh9th.mp4
> 
> That's because ur Ingame
It shouldn't crash in game anyway

**Comment by Exploriant** [comment]
> because

Some people's pcs can't handle it

**Comment by Rrhyast** [comment]
> > because
> 
> Some people's pcs can't handle it

WTF are u saying? I'm using this hack for fucking long time, recent updates fucked it up.

**Comment by Rrhyast** [comment]
> > > because
> > 
> > 
> > Some people's pcs can't handle it
> 
> WTF are u saying? I'm using this hack for fucking long time, recent updates fucked it up.

How Osiris & neps doesn't crash but for this one my pc can't handle it? That's bullshit reason.

**Comment by Rrhyast** [comment]
> > https://files.catbox.moe/sdh9th.mp4
> 
> Did u test loading the config after the crash when nothing is enabled?

Any method u think I've tested, still crash.

**Comment by Patrixsin** [comment]
> > > https://files.catbox.moe/sdh9th.mp4
> > 
> > 
> > Did u test loading the config after the crash when nothing is enabled?
> 
> Any method u think I've tested, still crash.

Try load the config while being dead. It was solution when I occured this crash problem on my paste

**Comment by Rrhyast** [comment]
> > > > https://files.catbox.moe/sdh9th.mp4
> > > 
> > > 
> > > Did u test loading the config after the crash when nothing is enabled?
> > 
> > 
> > Any method u think I've tested, still crash.
> 
> Try load the config while being dead. It was solution when I occured this crash problem on my paste

Bruh loading CFG in game with any method cause instant crash even in main menu.

**Comment by Patrixsin** [comment]
> > > > > https://files.catbox.moe/sdh9th.mp4
> > > > 
> > > > 
> > > > Did u test loading the config after the crash when nothing is enabled?
> > > 
> > > 
> > > Any method u think I've tested, still crash.
> > 
> > 
> > Try load the config while being dead. It was solution when I occured this crash problem on my paste
> 
> Bruh loading CFG in game with any method cause instant crash even in main menu.

have u tried to debug?

**Comment by Rrhyast** [comment]
> > > > > > https://files.catbox.moe/sdh9th.mp4
> > > > > 
> > > > > 
> > > > > Did u test loading the config after the crash when nothing is enabled?
> > > > 
> > > > 
> > > > Any method u think I've tested, still crash.
> > > 
> > > 
> > > Try load the config while being dead. It was solution when I occured this crash problem on my paste
> > 
> > 
> > Bruh loading CFG in game with any method cause instant crash even in main menu.
> 
> have u tried to debug?

Nah, I know how to debug, but I don't know how to attach the DLL from VS to the game when compiled.

**Comment by DLdota** [comment]
> > > > > > > https://files.catbox.moe/sdh9th.mp4
> > > > > > 
> > > > > > 
> > > > > > Did u test loading the config after the crash when nothing is enabled?
> > > > > 
> > > > > 
> > > > > Any method u think I've tested, still crash.
> > > > 
> > > > 
> > > > Try load the config while being dead. It was solution when I occured this crash problem on my paste
> > > 
> > > 
> > > Bruh loading CFG in game with any method cause instant crash even in main menu.
> > 
> > 
> > have u tried to debug?
> 
> Nah, I know how to debug, but I don't know how to attach the DLL from VS to the game when compiled.

need build in debug mode and use -insecure option to start csgo
then ctr+alt+p
to inject dll u can use LoadLibraryOne

then post here screenshoot with ur crash

**Comment by Rrhyast** [comment]
> > > > > > > > https://files.catbox.moe/sdh9th.mp4
> > > > > > > 
> > > > > > > 
> > > > > > > Did u test loading the config after the crash when nothing is enabled?
> > > > > > 
> > > > > > 
> > > > > > Any method u think I've tested, still crash.
> > > > > 
> > > > > 
> > > > > Try load the config while being dead. It was solution when I occured this crash problem on my paste
> > > > 
> > > > 
> > > > Bruh loading CFG in game with any method cause instant crash even in main menu.
> > > 
> > > 
> > > have u tried to debug?
> > 
> > 
> > Nah, I know how to debug, but I don't know how to attach the DLL from VS to the game when compiled.
> 
> need build in debug mode and use -insecure option to start csgo then ctr+alt+p to inject dll u can use LoadLibraryOne
> 
> then post here screenshoot with ur crash

It's fixed in latest update thanks for your help.
