### ISSUE TITLE
Invalid convar detected?

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#159]
![csgo_JV7sOlsJg4](https://user-images.githubusercontent.com/62977195/172214577-21a64e50-7a67-4885-aa04-9eaa32edc909.png)

**Comment by Patrixsin** [comment]
reveal money? I guess

**Comment by rrhyast** [comment]
@notgoodusename yo fix this shit please.
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/scripting/lilac/lilac_convar.sp
