### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#162]
Whenever I load up csgo, It loads fine, injects fine, everything works as it should. Once I load into a game however, the game crashes before I can even get into the game. How can i fix this?

**Comment by Rrhyast** [comment]
https://github.com/notgoodusename/OsirisAndExtra/issues/158
summary: don't turn off sv pure bypass

**Comment by Navoichyk** [comment]
> #158
> summary: don't turn off sv pure bypass

I didn’t, even if I don’t touch the menu at all. It just crashes when I load in gamr

**Comment by Rrhyast** [comment]
> > #158
> > summary: don't turn off sv pure bypass
> 
> I didn’t, even if I don’t touch the menu at all. It just crashes when I load in gamr

Strange, I've played with cheat for straight 2 hours without crash.

**Comment by Navoichyk** [comment]
> > > #158
> > > summary: don't turn off sv pure bypass
> > 
> > 
> > I didn’t, even if I don’t touch the menu at all. It just crashes when I load in gamr
> 
> Strange, I've played with cheat for straight 2 hours without crash.

wtf lol, can you send me your source and the dll? My discord is: Navoichyk#7777

**Comment by Rrhyast** [comment]
> > > > #158
> > > > summary: don't turn off sv pure bypass
> > > 
> > > 
> > > I didn’t, even if I don’t touch the menu at all. It just crashes when I load in gamr


> > 
> > 
> > Strange, I've played with cheat for straight 2 hours without crash.
> 
> wtf lol, can you send me your source and the dll? My discord is: Navoichyk#7777

No discord, only here: 
[Osiris.zip](https://github.com/notgoodusename/OsirisAndExtra/files/8884071/Osiris.zip)

**Comment by Navoichyk** [comment]
> > > > > #158
> > > > > summary: don't turn off sv pure bypass
> > > > 
> > > > 
> > > > I didn’t, even if I don’t touch the menu at all. It just crashes when I load in gamr
> 
> > > Strange, I've played with cheat for straight 2 hours without crash.
> > 
> > 
> > wtf lol, can you send me your source and the dll? My discord is: Navoichyk#7777
> 
> No discord, only here: [Osiris.zip](https://github.com/notgoodusename/OsirisAndExtra/files/8884071/Osiris.zip)

Can you send me your source? Whenever I compile it doesnt work

**Comment by Rrhyast** [comment]
> > > > > > #158
> > > > > > summary: don't turn off sv pure bypass
> > > > > 
> > > > > 
> > > > > I didn’t, even if I don’t touch the menu at all. It just crashes when I load in gamr
> > 
> > 
> > > > Strange, I've played with cheat for straight 2 hours without crash.
> > > 
> > > 
> > > wtf lol, can you send me your source and the dll? My discord is: Navoichyk#7777
> > 
> > 
> > No discord, only here: [Osiris.zip](https://github.com/notgoodusename/OsirisAndExtra/files/8884071/Osiris.zip)
> 
> Can you send me your source? Whenever I compile it doesnt work

It's the latest source from GitHub. Nothing different.
