### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Gleteur** [notgoodusename/OsirisAndExtra#163]
I can load the cheat but when I go in-game it crash i tried to put sv_pure to 1 and 0 still crashing.

**Comment by Navoichyk** [comment]
> I can load the cheat but when I go in-game it crash i tried to put sv_pure to 1 and 0 still crashing.

Yeah same thing was happening to me. If you want I can send you a dll for a working one. It has a good gui (not the best but yeah)
