### ISSUE TITLE
Crashes When Entering Game

### ISSUE THREAD

**Issue by PreGreko** [notgoodusename/OsirisAndExtra#169]
Hello , i downloaded and then compiled the source , when i inject it through csghost and try to load into a game it crashes , or when i am into the game and i inject , it crashes again

**Comment by PreGreko** [comment]
UPDATE : It Does This Only In Fullscreen

**Comment by DLdota** [comment]
i have the same problem with this commit 
[https://github.com/notgoodusename/OsirisAndExtra/commit/a33e395f01a5e525b1dceaf21cae6434b2366413](url)

**Comment by DLdota** [comment]
i have the same problem with #a33e395f01a5e525b1dceaf21cae6434b2366413

**Comment by PreGreko** [comment]
yuh
