### ISSUE TITLE
third person

### ISSUE THREAD

**Issue by LukluA** [notgoodusename/OsirisAndExtra#17]
fix third person not working please. 
the distance is broken.

![image](https://user-images.githubusercontent.com/89549104/147841127-c77f61ac-ef49-46d1-88c6-c3d1aa98a4bb.png)

**Comment by notgoodusename** [comment]
Its working fine for me, did you get a new update or something?

**Comment by ScottMTB** [comment]
oh must be something with my game then thanks for letting me know

**Comment by dapaster** [comment]
> oh must be something with my game then thanks for letting me know

how did you fix it?

**Comment by dapaster** [comment]
> Its working fine for me, did you get a new update or something?

for me the `thirdperson` is not working, but the official Osiris is working fine.. i notice its only happen with the old version of osiris, idk what causing this

**Comment by notgoodusename** [comment]
Try now
