### ISSUE TITLE
Mouse1 Keybinds

### ISSUE THREAD

**Issue by AimAssist** [notgoodusename/OsirisAndExtra#171]
Your unable to bind keys to the mouse1 button not sure if anyone has a fix for this or not.

**Comment by JannesBonk** [comment]
> Your unable to bind keys to the mouse1 button not sure if anyone has a fix for this or not.

for what are you trying to bind? for the legitbot u dont need to bind. Just disable silent and aimlock so when u shoot, it will target the enemy
