### ISSUE TITLE
Rage Config

### ISSUE THREAD

**Issue by issue1337** [notgoodusename/OsirisAndExtra#172]
Hello, can someone please post here their rage config?

**Comment by rrhyast** [comment]
[HVH.zip](https://github.com/notgoodusename/OsirisAndExtra/files/8996522/HVH.zip)
It's good for raging but bipolar for hvh cuz cheat isn't optimized for hvh.

**Comment by issue1337** [comment]
Thank you.

> [HVH.zip](https://github.com/notgoodusename/OsirisAndExtra/files/8996522/HVH.zip) It's good for raging but bipolar for hvh cuz cheat isn't optimized for hvh.

Thank you.
