### ISSUE TITLE
trying to make keystrokes but dont know why it is always in the debug window ?

### ISSUE THREAD

**Issue by nohardfeelings** [notgoodusename/OsirisAndExtra#173]
{
    if (!interfaces->engine->isConnected() || !interfaces->engine->isInGame() || !localPlayer->isAlive())
        return;

  if (!config->misc.keystrokes.enabled)
        return;

    int x, y;
    interfaces->engine->getScreenSize(x, y);

    //W

    if (GetAsyncKeyState(0X57)) {
        ImGui::Text("W"), (x / 2, y - 300, true, IM_COL32(220, 220, 220, 255));
    }

    ImGui::Text("_"), (x / 2, y - 300, true, IM_COL32(220, 220, 220, 255));

    //A

    if (GetAsyncKeyState(0X41)) {
        ImGui::Text("A"), (x / 2.1, y - 280, true, IM_COL32(220, 220, 220, 255));
    }

    ImGui::Text("_"), (x / 2.1, y - 280, true, IM_COL32(220, 220, 220, 255));

    //D

    if (GetAsyncKeyState(0x44)) {
        ImGui::Text("D"), (x / 1.9, y - 280, true, IM_COL32(220, 220, 220, 255));
    }

    ImGui::Text("_"), (x / 1.9, y - 280, true, IM_COL32(220, 220, 220, 255));

    //S

    if (GetAsyncKeyState(0x53)) {
        ImGui::Text("S"), (x / 2, y - 280, true, IM_COL32(220, 220, 220, 255));
    }

    ImGui::Text("_"), (x / 2, y - 280, true, IM_COL32(220, 220, 220, 255));
}

**Comment by Patrixsin** [comment]
U forgot about begin and end functions
`ImGuiWindowFlags windowFlags = ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize;

ImGui::Begin("Window name", nullptr, windowFlags); // this function
ImGui::Text("text example");
ImGui::End(); // this function`
