### ISSUE TITLE
Paste asus walls`

### ISSUE THREAD

**Issue by JukoiDev** [notgoodusename/OsirisAndExtra#177]
Yo, paste asus walls from https://github.com/lofcz/Osiris/blob/master/Osiris/Hacks/Visuals.cpp#L348-L369 , too lazy to make pr

**Comment by JukoiDev** [comment]
Visuals.cpp:
``
void Visuals::transparentWorld() noexcept
{
	if (!config->visuals.asusWalls)
	return;

	for (short h = interfaces->materialSystem->firstMaterial(); h != interfaces->materialSystem->invalidMaterial(); h = interfaces->materialSystem->nextMaterial(h)) {
	    const auto mat = interfaces->materialSystem->getMaterial(h);

	    const std::string_view textureGroup = mat->getTextureGroupName();

	    if (textureGroup.starts_with("World")) {
	            mat->alphaModulate(0.5);
	    }
	    if ((textureGroup.starts_with("StaticProp"))) {
	        
	        ConVar* static_Prop = interfaces->cvar->findVar("r_DrawSpecificStaticProp");
	        static_Prop->setValue(0);    
	        mat->alphaModulate(0.5);
	    }

	}
}
``

Visuals.h:
``
void transparentWorld() noexcept;
``

GUI.cpp:
``
ImGui::Checkbox("Asus walls", &config->visuals.asusWalls);
``

**Comment by JannesBonk** [comment]
if it was like customizable it would be great, i will try to make it like that for u and then send it

**Comment by Navoichyk** [comment]
> if it was like customizable it would be great, i will try to make it like that for u and then send it

If you do this, respond to this. That’d be really cool!

**Comment by notgoodusename** [comment]
> If you do this, please respond to this. That’d be really cool!

https://github.com/notgoodusename/OsirisAndExtra/commit/973bb69acb45a9b40216070c2e0589836e818f39

**Comment by Navoichyk** [comment]
> > If you do this, please respond to this. That’d be really cool!
> 
> [973bb69](https://github.com/notgoodusename/OsirisAndExtra/commit/973bb69acb45a9b40216070c2e0589836e818f39)

I love you :)

**Comment by JukoiDev** [comment]
thx
