### ISSUE TITLE
C+P Nade timer

### ISSUE THREAD

**Issue by JukoiDev** [notgoodusename/OsirisAndExtra#178]
src https://github.com/danielkrupinski/Osiris/pull/3125

**Comment by Navoichyk** [comment]
> src [danielkrupinski/Osiris#3125](https://github.com/danielkrupinski/Osiris/pull/3125)

this would be really nice, but for molotove too

**Comment by JukoiDev** [comment]
exactly

**Comment by Navoichyk** [comment]
> exactly

I tried adding it, and was successful. But there were some minor differences between the cheats that I didn’t know how to work around, so it didn’t work sadly

**Comment by JukoiDev** [comment]
bump, @notgoodusename could you add this feature to your TODO?

**Comment by JukoiDev** [comment]
thank you
