### ISSUE TITLE
Add Aimbot Fov

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#181]
I thought I could ask this in the pull requests, but I couldn't figure it out lol. Anyways, I think aimbot fov would be very useful and a good feature to add, the only place I have found that might be helpful is here: https://github.com/danielkrupinski/Osiris/pull/3127/files
I've tried pasting it in but i keep getting errors and I'm honestly stuck. This would be verryyy good and useful!

edit: I think the 'add fov' link or whatever i sent is broken aswell so idk if its really useful

**Comment by JannesBonk** [comment]
> I thought I could ask this in the pull requests, but I couldn't figure it out lol. Anyways, I think aimbot fov would be very useful and a good feature to add, the only place I have found that might be helpful is here: https://github.com/danielkrupinski/Osiris/pull/3127/files
> I've tried pasting it in but i keep getting errors and I'm honestly stuck. This would be verryyy good and useful!
> 
> edit: I think the 'add fov' link or whatever i sent is broken aswell so idk if its really useful

just make pull request or add it for urself

**Comment by Navoichyk** [comment]
> > I thought I could ask this in the pull requests, but I couldn't figure it out lol. Anyways, I think aimbot fov would be very useful and a good feature to add, the only place I have found that might be helpful is here: https://github.com/danielkrupinski/Osiris/pull/3127/files
> > I've tried pasting it in but i keep getting errors and I'm honestly stuck. This would be verryyy good and useful!
> > edit: I think the 'add fov' link or whatever i sent is broken aswell so idk if its really useful
> 
> just make pull request or add it for urself

How do I make a request? I couldn’t figure it out.
