### ISSUE TITLE
no ragebot update?

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#182]
:/ This heck has potential to tap any cheat.

**Comment by Navoichyk** [comment]
It needs a couple features to really assist in that. Like force safepoints, Baim, min damage override, etc.

**Comment by JukoiDev** [comment]
we really need to force this cheat's development

**Comment by issue1337** [comment]
> we really need to force this cheat's development

Exactly. Its actually decent, and has great potential.
