### ISSUE TITLE
Add ragdoll chams

### ISSUE THREAD

**Issue by JukoiDev** [notgoodusename/OsirisAndExtra#183]
```
// ADD THIS IN RENDER
if (entity && !entity->isDormant() && entity->getClientClass()->classId == ClassId::CSRagdoll)
    renderRagdolls(entity);

void Chams::renderRagdolls(Entity* player) noexcept
{
  if (!localPlayer)
    return;
  
  applyChams(config->chams["Ragdolls"].materials);
}
```
Again, don;t want to pullrequest. Add this to render in chams.cpp

**Comment by JukoiDev** [comment]
if some xy0 paster didn;t understand my first comment: 
![image](https://user-images.githubusercontent.com/79868869/177052539-3878a869-9952-4efe-a4e5-981cc82345e5.png)

**Comment by KisSsArt** [comment]
wrong code

**Comment by JukoiDev** [comment]
?? wdym, this is working

**Comment by JukoiDev** [comment]
also bro @KisSsArt i saw ur CopyPastaNoob's cheat

**Comment by Navoichyk** [comment]
> also bro @KisSsArt i saw ur CopyPastaNoob's cheat, which was(it is iindeed deleted) based on GOESP+qo0 lol

Oof lol

**Comment by JukoiDev** [comment]
Created pull request

**Comment by JukoiDev** [comment]
Maybe we'll fix it with fl frozen
