### ISSUE TITLE
Any plans to add a spinbot or something like that

### ISSUE THREAD

**Issue by GetRektLOL** [notgoodusename/OsirisAndExtra#19]
Would be great

**Comment by GetRektLOL** [comment]
Most of the code is already there, would make sense to add it

**Comment by notgoodusename** [comment]
[Done](https://github.com/notgoodusename/OsirisAndExtra/commit/d3473d0677a1d37dd48279b7009adca539eb1ffa)

**Comment by GetRektLOL** [comment]
dude thank you, you might be the fastest developer i have ever seen

**Comment by GetRektLOL** [comment]
Hey, i cant seem to find the option for spin in the anti aim section or am i just dumb

**Comment by GetRektLOL** [comment]
never mind, i was just dumb
