### ISSUE TITLE
Crashing cause of slowed down indicator


### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#192]

**Comment by notgoodusename** [comment]
It isnt crashing for me, could you tell me when does it crash for you?

**Comment by JannesBonk** [comment]
> It isnt crashing for me, could you tell me when does it crash for you?

When loading a config that has slowed down indicatir in it

**Comment by notgoodusename** [comment]
And what does it say?

**Comment by JannesBonk** [comment]
> And what does it say?

nvm bro i just fixed with adding that round at the indicator
