### ISSUE TITLE
Paste weave resolver lol

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#204]
I know its probably either dog shit or too hard, but idk. I got an old source and thought maybe it'd be helpful/useful?
[weave-master.zip](https://github.com/notgoodusename/OsirisAndExtra/files/9068093/weave-master.zip)

**Comment by Navoichyk** [comment]
[weave-master.zip](https://github.com/notgoodusename/OsirisAndExtra/files/9068108/weave-master.zip)
here's the whole source, idk if itll be useful but yeah.

**Comment by rrhyast** [comment]
> I know its probably either dog shit or too hard, but idk. I got an old source and thought maybe it'd be helpful/useful? [weave-master.zip](https://github.com/notgoodusename/OsirisAndExtra/files/9068093/weave-master.zip)

just remind you this hack is not a paste. its a forks from orisis with the enhancements that og osiris should have since 2018 not still stand being a dry sdk today. but anyway he only merging from pull requests not issues(idk why)  because I shared no recoil few months ago but instead we have a crappy rcs now.

**Comment by notgoodusename** [comment]
> just remind you this hack is not a paste. its a forks from orisis with the enhancements that og osiris should have since 2018, but it stand  to being a dry sdk. but anyway he only merging from pull requests not issues(idk why)  because I shared no recoil few months ago but instead we have a crappy rcs now.

Pull requests require less time and are easier to implement, also is rcs really that crappy?

**Comment by Navoichyk** [comment]
> > just remind you this hack is not a paste. its a forks from orisis with the enhancements that og osiris should have since 2018, but it stand  to being a dry sdk. but anyway he only merging from pull requests not issues(idk why)  because I shared no recoil few months ago but instead we have a crappy rcs now.
> 
> Pull requests require less time and are easier to implement, also is rcs really that crappy?

Honestly, i got the new source and have been using it. But the rcs is so bad that i just never use it. Its basically jsut a really bad recoil script

**Comment by notgoodusename** [comment]
> Honestly, i got the new source and have been using it. But the rcs is so bad that i just never use it. Its basically jsut a really bad recoil script

Alright, i will try to fix it

**Comment by notgoodusename** [comment]
Just fixed it, there is just a small problem and that is that silent rcs is pretty obvious when you stop shooting, but thats about it

**Comment by Navoichyk** [comment]
> Just fixed it, there is just a small problem and that is that silent rcs is pretty obvious when you stop shooting, but thats about it

do you still have to do the sliders and stuff?
