### ISSUE TITLE
Save location of watermark & spectator list in config and load on loading new config

### ISSUE THREAD

**Issue by 2lag** [notgoodusename/OsirisAndExtra#205]
Pretty self explanatory I feel, would be pretty easy feature to implement I believe.

**Comment by 2lag** [comment]
Also, skin changer in its entirety is broken afaik

**Comment by notgoodusename** [comment]
Spectator list is already saved, not watermark tho
also the skinchanger works totally fine, you sure you enabled it?

**Comment by Navoichyk** [comment]
> Spectator list is already saved, not watermark tho also the skinchanger works totally fine, you sure you enabled it?

How could i make the watermark, keybinds list, purchase list, etc save on config?

**Comment by notgoodusename** [comment]
> How could i make the watermark, keybinds list, purchase list, etc save on config?

[How spectatorList is declared](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Config.h#L339-L345)
[How spectatorList is save](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Config.cpp#L1039-L1047)
[And how spectatorList is loaded](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Config.cpp#L481-L486)

**Comment by notgoodusename** [comment]
> ![image](https://user-images.githubusercontent.com/105137324/178088556-9b68a0c5-74e9-4265-8150-86bcb56fa176.png) this stuff?

That stuff is for when you load a cfg and have a position saved

**Comment by Navoichyk** [comment]
> > How could i make the watermark, keybinds list, purchase list, etc save on config?
> 
> [How spectatorList is declared](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Config.h#L339-L345) (Look at pos) [How spectatorList is saved](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Config.cpp#L1039-L1047) [And how spectatorList is loaded](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Config.cpp#L481-L486)
> 
> That should give you and idea on how to save it

![image](https://user-images.githubusercontent.com/105137324/178117316-5ab82b73-7508-4da4-ae30-ad37e2129e1d.png)
if that is how you save it, shouldnt keybind list's location be saved too because its the same?

**Comment by Navoichyk** [comment]
It looks like keybindlist, and spectator list is saved, and loaded the exact same way so i dont understand why keybind list isnt saving location

**Comment by Navoichyk** [comment]
![image](https://user-images.githubusercontent.com/105137324/178117424-f2d690a4-2801-4791-9991-6f06da989865.png)
like this?

**Comment by 2lag** [comment]
fixed :D tysm for the pointers it was way easier than i thought it'd be

**Comment by Navoichyk** [comment]
> fixed :D tysm for the pointers it was way easier than i thought it'd be

Can you show me how you did it?

**Comment by NeurAIGod** [comment]
Why was this issue closed? The project still contains this error. Just because you solved it personally on your local instance doesn't mean that this issue has been fixed. @notgoodusename can you please reopen it until it actually has been resolved?

**Comment by 2lag** [comment]
> > fixed :D tysm for the pointers it was way easier than i thought it'd be
> 
> Can you show me how you did it?

I did it with exactly what you showed me in the code! I just adapted each of the settings to have the setting within the config files to save the location of any window that would be open. You can make it just one command and call it in every function where it is needed, or you can copy the exact code and change the reference names in every function where it is needed. 

NeurAIGod, I closed this thread because I thought it is a pretty self explanatory fix after you're able to find the location of what you're trying to work on. Sorry for any confusion, but I believe the issue has been resolved as of the most recent commits today, thanks to your pull request!

**Comment by NeurAIGod** [comment]
> NeurAIGod, I closed this thread because I thought it is a pretty self explanatory fix after you're able to find the location of what you're trying to work on. 

Since I think that you are new to Workflows allow me to elaborate:
One can open issues for issues and questions, however they should only be closed whenever the question was answered or a fix was implemented. Closing an issue is the same as saying that it has been resolved and requires no further action thus a request could be forgotten. No matter how simple the fix is, if it's a legitimate issue it should stay open unless resolved.

Sidenote: if one asks a question it should be obvious that it is a question and not an issue.
