### ISSUE TITLE
Custom Clantag Stays on

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#207]
Even if I set the custom clantag checkbox unticked, the clantag stays. How can i make it where if its unchecked, the clantag disppears

**Comment by Patrixsin** [comment]
u can use custom clantag with clear text in it then disable or u can use `cl_clanid 0` command to clear clantag

**Comment by NeurAIGod** [comment]
> u can use custom clantag with clear text in it then disable or u can use `cl_clanid 0` command to clear clantag

While this works it would not restore the original clantag if one has one. This would require saving the original clantag somewhere and restoring on disabling. However it's not so straightforward as loading a config needs to be handled too.

**Comment by Navoichyk** [comment]
> u can use custom clantag with clear text in it then disable or u can use `cl_clanid 0` command to clear clantag

how specifically would i do this?
