### ISSUE TITLE
Is this detected?

### ISSUE THREAD

**Issue by GetRektLOL** [notgoodusename/OsirisAndExtra#21]
![VAC](https://user-images.githubusercontent.com/92521923/147876709-28803804-fe3e-4f46-acd6-bc81579b06bd.png)
Was playing full rage mode with csghost vac bypass and also tested process hacker 2 and got this, doesnt happen with the regular osiris build. Verifying integrity of game files seems to fix it for some time. I

**Comment by notgoodusename** [comment]
Weird, I never got a message like that, and yes, this cheat is most likely detected so using a vac bypass is necessary

**Comment by GetRektLOL** [comment]
yeah i dont know why i got this too, but anyway it's gone now. Are you thinking of adding tickbase and resolver because it's kinda important but anyway thanks for making this cheat

**Comment by GetRektLOL** [comment]
i know there is a pr for the tickbase and resolver but it errors out in visual studio

**Comment by voidzer0-development** [comment]
Angle delta => 39.f in casual servers will cause this so make sure you clamp there
