### ISSUE TITLE
skin changer still not working

### ISSUE THREAD

**Issue by 2lag** [notgoodusename/OsirisAndExtra#213]
i'm trying to make it very simple by just having it be a vanilla knife changer, no skins, no wear, only a nametag and the vanilla knife, but enabling the option, selecting the knife, and then pressing update, nothing changes what so ever. any help would be much appreciated!

**Comment by Navoichyk** [comment]
> i'm trying to make it very simple by just having it be a vanilla knife changer, no skins, no wear, only a nametag and the vanilla knife, but enabling the option, selecting the knife, and then pressing update, nothing changes what so ever. any help would be much appreciated!

I’m not currently at home. But I’ve done something like this before. It was actually quite simple. All I did was comment out all the other guns, and all the unwanted features, and it worked perfectly for me. If you want I can try to do it again once I’m home (will be a few hours)?

**Comment by 2lag** [comment]
that sounds fantastic! i can add you on discord or something and we can talk there, or just through this thread until its completed, whatever works!

**Comment by Navoichyk** [comment]
> that sounds fantastic! i can add you on discord or something and we can talk there, or just through this thread until its completed, whatever works!

I would much prefer discord haha. I hate these threads. My discord is Hiraeth#0001

**Comment by 2lag** [comment]
gotcha! i'll add you right now

**Comment by NeurAIGod** [comment]
Cannot reproduce, was able to change to vanilla knives. Did you forget to enable them? Please attach screenshots or a video.

**Comment by Navoichyk** [comment]
> Cannot reproduce, was able to change to vanilla knives. Did you forget to enable them? Please attach screenshots or a video.

It’s simple. He just wants a skin changer specifically for knives changer. I’ve done it before and it’s pretty simple

**Comment by NeurAIGod** [comment]
But that exists already, so what's the issue

**Comment by Navoichyk** [comment]
> But that exists already, so what's the issue

He only wants the skin changer to show knife changer, no guns no nothing. Only change knives

**Comment by NeurAIGod** [comment]
> He only wants the skin changer to show knife changer, no guns no nothing. Only change knives

But that's not an "issue" then as that is merely a subset of already existing features. Thus creating an issue per se does not make much sense. Do not confuse "questions" with "issues".

**Comment by 2lag** [comment]
It wasn't working for me, I have since then gotten it fixed. There were indeed no issues in this case, it was just not working for some reason until I relocated the features.
