### ISSUE TITLE
LAST THING I SWEAR (major legitbot issue)

### ISSUE THREAD

**Issue by 2lag** [notgoodusename/OsirisAndExtra#214]
with hotkey2, you arent able to bind mouse1, so the best other option is to leave it on all the time and turn on silent aim, and keep aimlock off. the ideal option however, would be enabling the option to bind to mouse1, so the legit bot can truly be hidden until it is needed/used. thanks! 💯

**Comment by NeurAIGod** [comment]
How is binding mouse one different from having it set to always on? The moment you press mouse 1 you will shoot at which point the aimbot will kick in (unless you have auto shoot enabled).

**Comment by 2lag** [comment]
in spectate, it locks before you press mouse 1. thats is why

**Comment by 2lag** [comment]
yessir! exactly that, i just want to be able to look "legit"ish with the legit bot hahaha

**Comment by NeurAIGod** [comment]
> in spectate, it locks before you press mouse 1. thats is why

I was bothered by this claim as I was fairly certain that that's not how it works. Just to make sure I'm not missing anything in the code I tried it with a friend who spectates me.

The following settings will only flick when you shoot (smoothing set to 1 so it's more obvious) and as you can see I did not bind mouse 1 thus this is rather unnecessary. Feel free to test it out yourself.

![image](https://user-images.githubusercontent.com/108984995/178156245-98d18e15-7d8e-4c7b-8a51-f637c3484dd8.png)

Of course if you were to toggle aimlock you would lock onto their heads beforehand but why would you do that if you don't want that behaviour.

Also if you were to look into the code you would see that at [Legitbot.cpp#L86](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/Legitbot.cpp#L86) the check only passes if either aimlock is turned on or localplayer is currently shooting (`IN_ATTACK ` to be exact).

So no it doesn't make sense imo.

**Comment by 2lag** [comment]
Try these settings:
Enable for all, aimlock on (or off doesn't seem to matter), silent on, visible only off, scoped only off, ignore flash and smoke, killshot on, and rcs with silent rcs maxed out, and set FOV to 10. I think in your config its the scoped only but I may be wrong. I'm only saying this because I literally gave out the dll to play with some friends and I literally saw it happen. Once they got within 10 FOV of the enemy it would just snap to them. I can send a match download link if you don't believe me, but I'm simply telling you what I saw!

**Comment by 2lag** [comment]
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-Nqc4A-H4nCn-MO2wz-96Sxm-TO2xK
spectate anti or the cat face person on T side

**Comment by NeurAIGod** [comment]
Aimlock does matter, a lot actually. I also just sent you the code which proves my statement. Viewangles are only written when you are either attacking or have aimlock on (of course weapon needs to be enabled). Scoped has nothing to do in this case (see code) also I tested using a Glock so the scope check doesn't matter to begin with. Match download doesn't help me without seeing exactly what settings where used. I urge to test it again with a friend spectating you in a bot match. Also just to say it once more, do NOT tick aimlock if you don't want to lock onto enemies before shooting because that's exactly what it is for.

**Comment by 2lag** [comment]
here is the config i use, please test it out and let me know if you are able to recreate the issue
```
{
  "Backtrack": {
    "Enabled": true,
    "Ignore flash": true,
    "Ignore smoke": true,
    "Time limit": 50
  },
  "Chams": {
    "Allies": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Backtrack": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Defusing": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Desync": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Enemies": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Hands": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Local player": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Sleeves": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Weapons": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    }
  },
  "ESP": {
    "Enemies": {
      "All": {
        "Box": {
          "Alpha": 1.0,
          "Color": "#ff0000",
          "Enabled": true,
          "Rainbow Speed": 13.0,
          "Type": 1
        },
        "Enabled": true,
        "Health Bar": {
          "Alpha": 0.0,
          "Color": "#a4a4a4",
          "Enabled": true,
          "Type": 1
        },
        "Name": {
          "Enabled": true
        },
        "Skeleton": {
          "Alpha": 1.0,
          "Color": "#82648b",
          "Enabled": true
        }
      }
    }
  },
  "Legitbot": [
    {
      "Between shots": true,
      "Enabled": true,
      "Fov": 10.8,
      "Hitboxes": 1,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Killshot": true,
      "RCS Horizontal": 1.0,
      "RCS Vertical": 1.0,
      "Recoil control system": true,
      "Silent": true,
      "Silent RCS": true
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Misc": {
    "Auto accept": true,
    "Auto pistol": true,
    "Bunny hop": true,
    "Edge Bug": true,
    "Edge Bug Key": {
      "Key": "C",
      "Key mode": 2
    },
    "Edge Jump Key": {
      "Key": "MOUSE4",
      "Key mode": 0
    },
    "Jump Bug": true,
    "Jump Bug Key": {
      "Key": "MOUSE5",
      "Key mode": 2
    },
    "Long Jump": true,
    "Long Jump Key": {
      "Key": "MOUSE4",
      "Key mode": 2
    },
    "Mini Jump": true,
    "Mini Jump Key": {
      "Key": "MOUSE2",
      "Key mode": 2
    },
    "Noscope crosshair": {
      "Enabled": true
    },
    "Pixel Surf": true,
    "Pixel Surf Key": {
      "Key": "LSHIFT",
      "Key mode": 2
    },
    "Pred Amnt": 32,
    "Spectator list": {
      "Enabled": true
    },
    "Watermark": {
      "Enabled": true,
      "Pos": {
        "X": -18.0,
        "Y": -19.0
      }
    }
  },
  "Ragebot": [
    {
      "Min damage": 1
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Skin changer": [
    {
      "Custom name": "lol",
      "Enabled": true
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Sound": {
    "Players": [
      {},
      {},
      {}
    ]
  },
  "Triggerbot": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Visuals": {
    "Deagle spinner": true,
    "Hit marker": true,
    "Hit marker time": 0.5,
    "Map color": {
      "Color": [
        0.6509434,
        0.46364367,
        0.61737084
      ],
      "Rainbow Speed": 14.4
    },
    "Motion Blur": {
      "Enabled": true,
      "Forward": true
    },
    "No aim punch": true,
    "No view bob": true,
    "No view punch": true,
    "Playermodel CT": 54,
    "Playermodel T": 54,
    "Wireframe molotov": true,
    "Wireframe smoke": true
  }
}
```

**Comment by 2lag** [comment]
Also, it may have some extra features so just delete them from the comments (only movement stuff I believe)

**Comment by NeurAIGod** [comment]
Sure, will try out when I get the chance again.

**Comment by 2lag** [comment]
Cool! Thank you for being so willing to work with me!!

**Comment by NeurAIGod** [comment]
I tested your config even though I showed you how the code works which already made my statement 100% but here videos just proof it again:
Mouse clicks are visualised.

**Default:**

https://user-images.githubusercontent.com/108984995/178250238-9d94bd0f-77ac-406a-b095-f4133eb0c77d.mp4

**Turning off `Silent`:**

https://user-images.githubusercontent.com/108984995/178250723-f0e2af77-2cc9-4683-9a7c-f54598948a41.mp4

**Turning on `Silent` & `Aimlock`:**

https://user-images.githubusercontent.com/108984995/178250854-3db74b36-8317-452e-bed8-6bf671f848c0.mp4

**Note:**

I really advise you to not use `Silent` if you want to act legit, you should see how you are locking onto enemies to adjust your playstyle and config else you'll end up playing rather blatant.

**For the future:**

I already showed you proof how you statement is wrong, I urge you to learn how to read code or test things for yourself and not holding onto your belief unless I show you video proof which is worth way less than showing you exactly how the code works. I won't be doing this the next time.

**Comment by 2lag** [comment]
That is completely understandable, and I will definitely take your word for it, but in the SilentAndAimlock video, it is doing exactly what I told you it was doing. When the crosshair is brought within your FOV to their head, it will automatically lock and stay locked until you bring the crosshair back away from the head. I do believe this is in fact an issue. I did test it myself and that is how I identified it in the first place, no matter what the section of code you're looking at may say.

**Comment by NeurAIGod** [comment]
> That is completely understandable, and I will definitely take your word for it, but in the SilentAndAimlock video, it is doing exactly what I told you it was doing. When the crosshair is brought within your FOV to their head, it will automatically lock and stay locked until you bring the crosshair back away from the head. I do believe this is in fact an issue. I did test it myself and that is how I identified it in the first place, no matter what the section of code you're looking at may say.

The `SilentAndAimlock` video is exactly what I said happens when you turn on **Aimlock**. This does not invalidate any of my statements but it exactly shows what I have been saying all along.

Let me quote:
> Also if you were to look into the code you would see that at [Legitbot.cpp#L86](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/Legitbot.cpp#L86) the check only passes if either **aimlock is turned on** or localplayer is currently shooting (IN_ATTACK to be exact).

> **Aimlock does matter, a lot actually**. I also just sent you the code which proves my statement. Viewangles are only written when you are either attacking **or have aimlock on** (of course weapon needs to be enabled). [...] Also just to say it once more, **do NOT tick aimlock if you don't want to lock onto enemies before shooting because that's exactly what it is for**.

To finalise this:

Binding M1 to Legitbot is completely useless as legitbot is already made to activate `IN_ATTACK` with the exception being if you have Aimlock turned on which you obviously DO NOT WANT. This locking behaviour is exactly what aimlock is for **this is intended**.

Binding M1 to Legitbot might even be worse depending on the order how keybinds get checked (would need to look at the code again) as in theory if legitbot runs before keybinds get checked it could lead to you shooting, then activating legitbot and thus missing before you even flick (as I said one sentence prior this depends on the order in the code which I do not know by heart).

**Comment by 2lag** [comment]
Yeah... I kinda realized that
