### ISSUE TITLE
Aim Fov Not Configable per gun, and is extremely innaccurate.

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#217]
I know i was bugging about getting it added, and not trying to be a bitch and annoy you about it. With that being said its extremely extremely inaccurate. 

For Example:
![image](https://user-images.githubusercontent.com/105137324/178158725-c79c0841-b75a-43b0-b1a5-2045d1249ae2.png)

My Fov with pistols is set to where i have to practically be right on the person for it to lock on aimbot, yet the fov shows it that large.

**Comment by Fearqueesha** [comment]
how did you get it to even show up??

**Comment by Navoichyk** [comment]
> how did you get it to even show up??

What do you mean? I just copied exactly how notgoodusename did it

**Comment by notgoodusename** [comment]
I dont plan to make aim fov to be configurable on every weapon, since it would be really annoying
Also check if its fixed for you

**Comment by Navoichyk** [comment]
> I dont plan to make aim fov to be configurable on every weapon, since it would be really annoying Also check if its fixed for you

Can i have your discord? Mines Hiraeth#0001 if you wanna add me

**Comment by notgoodusename** [comment]
> Hiraeth#0001

Added

**Comment by notgoodusename** [comment]
> how did he do it? it isn't in the pull requests or anything

download the latest repo
