### ISSUE TITLE
Tab Color

### ISSUE THREAD

**Issue by Fearqueesha** [notgoodusename/OsirisAndExtra#218]
I want to change the colors of the menu but the only part I am having trouble with is the tabs. i try changing the header and nothing happens. I have tried several things and can't find a way. Am I doing something wrong? 

![Screenshot 2022-07-10 183947](https://user-images.githubusercontent.com/109046048/178164780-87ff6c77-5b41-4fea-962f-ca40ac3fb7c1.png)

![Screenshot 2022-07-10 183924](https://user-images.githubusercontent.com/109046048/178164781-f47f2f3c-4800-4316-9721-35840a49fa90.png)

**Comment by notgoodusename** [comment]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2265-L2268

**Comment by Fearqueesha** [comment]
> https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2265-L2268

these aren't the tabs, this is just the background and the 2nd tabs. I mean the bain tabs like these


![Screenshot 2022-07-10 222959](https://user-images.githubusercontent.com/109046048/178177694-d3e7595e-c428-45bb-b67f-a6f77d33ba91.png)

**Comment by notgoodusename** [comment]
> ![Screenshot 2022-07-10 222959](https://user-images.githubusercontent.com/109046048/178177694-d3e7595e-c428-45bb-b67f-a6f77d33ba91.png)

if you look around the same func you will see that the colors are changed in different ways

https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2187-L2199

https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2311-L2313

https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2311-L2313

**Comment by Fearqueesha** [comment]
> > ![Screenshot 2022-07-10 222959](https://user-images.githubusercontent.com/109046048/178177694-d3e7595e-c428-45bb-b67f-a6f77d33ba91.png)
> 
> if you look around the same func you will see that the colors are changed in different ways
> 
> https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2187-L2199
> 
> https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2311-L2313
> 
> https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/GUI.cpp#L2311-L2313

yes, but what do I change? I just want to change the color. I can change the color of everything else on the menu except for the main tabs. I have tried almost everything now. is there just a clear spot to change them or something? I want to make them a really light grey.

**Comment by notgoodusename** [comment]
> yes, but what do I change? I just want to change the color. I can change the color of everything else on the menu except for the main tabs. I have tried almost everything now. is there just a clear spot to change them or something? I want to make them a really light grey.

I literally gave you the lines where the color of the main tabs changes

**Comment by Fearqueesha** [comment]
> > yes, but what do I change? I just want to change the color. I can change the color of everything else on the menu except for the main tabs. I have tried almost everything now. is there just a clear spot to change them or something? I want to make them a really light grey.
> 
> I literally gave you the lines where the color of the main tabs changes

it does nothing to the tabs. I changed exactly what you gave me. this is what I got.

![Screenshot 2022-07-11 074729](https://user-images.githubusercontent.com/109046048/178257938-87df809b-dd9e-48aa-88a3-b14093756391.png)

![Screenshot 2022-07-11 074746](https://user-images.githubusercontent.com/109046048/178257964-bacd8a9f-ba65-4af2-b083-e4aa44dc49d5.png)

![Screenshot 2022-07-11 074845](https://user-images.githubusercontent.com/109046048/178257978-a92b03ff-04f2-41ad-b59d-5b894f8d2589.png)

**Comment by Fearqueesha** [comment]
sorry i figured it out lol
