### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by freegocrazy** [notgoodusename/OsirisAndExtra#22]
when i build i get these errors (debug and release have same results)
![image](https://user-images.githubusercontent.com/95655410/148630038-a030ef7f-1cdb-406d-9089-1c7e909cb48f.png)

**Comment by freegocrazy** [comment]
there are more errors but those are some of them

**Comment by freegocrazy** [comment]
why did you close this

**Comment by notgoodusename** [comment]
This error doesnt happen, and idk how to fix your error
