### ISSUE TITLE
autostop for legitbot

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#225]
useful when semi raging

**Comment by Xsintashi** [comment]
aint ragebot for semi better?

**Comment by rrhyast** [comment]
> aint ragebot for semi better?

sometimes most of the people don't cheating either so its more closet using  on legitbot than ragebot.

**Comment by Navoichyk** [comment]
> > aint ragebot for semi better?
> 
> sometimes most of the people don't cheating either so its more closet using on legitbot than ragebot.

But semi raging isnt legit at all and is extremely obvious. Plus the cheat is set up in a way that you can use ragebot for semi way better than legitbot
