### ISSUE TITLE
Issue with Cristyanul's fork

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#241]
There's the issue with dt and hideshots that causes you to get kicked out of games pretty quickly. There's another issue where throwing grenades also causes you to get kicked from games. There are a couple other issues, but right now those are the only things I have noticed currently that really need to be fixed.

**Comment by dctrlight** [comment]
are you stupid
?

**Comment by Navoichyk** [comment]
> are you stupid
> ?

Yeah pretty much. I know it’s a fork and everything I’m just seeing if it’s being worked on or not. No need to be a cunt for no reason. Have a good day 👍

**Comment by Liam5750** [comment]
> are you stupid ?

infact I am. My iq is atleast higher then yours(30 iq btw beat that dog)

**Comment by Xsintashi** [comment]
close this

**Comment by rrhyast** [comment]
> close this

he's fucking right close it.
