### ISSUE TITLE
No Recoil 

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#243]
https://github.com/pseuxide/Dainsleif/blob/master/Dainsleif/Hacks/AntiRecoil.cpp
RN I really don't know how to do Pull Requests and busy with other works. I tried this and this is t**he best no recoil** i used since 2019 please someone merge it. Its 100 times better than RCS. Also add it to misc section to be easily useable at legitbot & ragebot.

**Comment by Navoichyk** [comment]
> https://github.com/pseuxide/Dainsleif/blob/master/Dainsleif/Hacks/AntiRecoil.cpp
> RN I really don't know how to do Pull Requests and busy with other works. I tried this and this is t**he best no recoil** i used since 2019 please someone merge it. Its 100 times better than RCS. Also add it to misc section to be easily useable at legitbot & ragebot.

Add me on discord: Hiraeth#0001. I neeeed this code lmfao!

**Comment by rrhyast** [comment]
> > https://github.com/pseuxide/Dainsleif/blob/master/Dainsleif/Hacks/AntiRecoil.cpp
> > RN I really don't know how to do Pull Requests and busy with other works. I tried this and this is t**he best no recoil** i used since 2019 please someone merge it. Its 100 times better than RCS. Also add it to misc section to be easily useable at legitbot & ragebot.
> 
> Add me on discord: Hiraeth#0001. I neeeed this code lmfao!

I don't have discord

**Comment by Navoichyk** [comment]
> > > https://github.com/pseuxide/Dainsleif/blob/master/Dainsleif/Hacks/AntiRecoil.cpp
> > > RN I really don't know how to do Pull Requests and busy with other works. I tried this and this is t**he best no recoil** i used since 2019 please someone merge it. Its 100 times better than RCS. Also add it to misc section to be easily useable at legitbot & ragebot.
> > 
> > 
> > Add me on discord: Hiraeth#0001. I neeeed this code lmfao!
> 
> I don't have discord

That’s depressing, can you upload your code and send a link here? I wanna see how you implemented it. I always have an issue doing it from daniels to this

**Comment by rrhyast** [comment]
> > > > https://github.com/pseuxide/Dainsleif/blob/master/Dainsleif/Hacks/AntiRecoil.cpp
> > > > RN I really don't know how to do Pull Requests and busy with other works. I tried this and this is t**he best no recoil** i used since 2019 please someone merge it. Its 100 times better than RCS. Also add it to misc section to be easily useable at legitbot & ragebot.
> > > 
> > > 
> > > Add me on discord: Hiraeth#0001. I neeeed this code lmfao!
> > 
> > 
> > I don't have discord
> 
> That’s depressing, can you upload your code and send a link here? I wanna see how you implemented it. I always have an issue doing it from daniels to this

Actually I compiled dainsleif and test it on csgo. The only good option this hack had was no recoil. Also check the linked repository, you'll find more.

**Comment by notgoodusename** [comment]
This repo has the same code, the current rcs system works just as well

**Comment by rrhyast** [comment]
> This repo has the same code, the current rcs system works just as well

Bruh, This one is enable and shoot. nobody get brain fuck to set x y for rcs per weapon.

**Comment by notgoodusename** [comment]
> Bruh, This one is enable and shoot. nobody get brain fuck to set x y for rcs per weapon.

Just set both x and y to 1 and you have the same result
And the recoil system isnt configurable for every weapon, once you enable it, it enables it for every weapon

**Comment by rrhyast** [comment]
> > Bruh, This one is enable and shoot. nobody get brain fuck to set x y for rcs per weapon.
> 
> Just set both x and y to 1 and you have the same result And the recoil system isnt configurable for every weapon, once you enable it, it enables it for every weapon

ok but ragebot doesn't have it. why?

**Comment by notgoodusename** [comment]
> ok but ragebot doesn't have it. why?

Ragebot does have no recoil, it just isnt an option to enable or disable

**Comment by Navoichyk** [comment]
> > ok but ragebot doesn't have it. why?
> 
> Ragebot does have no recoil, it just isnt an option to enable or disable

And too add to that there’s zero reason no recoil should be able to be toggled on and off for rage or lol

**Comment by notgoodusename** [comment]
Added new rcs struct so there is no need to cfg every weapon + set default vertical and horizontal values to 1

**Comment by rrhyast** [comment]
> > Bruh, This one is enable and shoot. nobody get brain fuck to set x y for rcs per weapon.
> 
> Just set both x and y to 1 and you have the same result And the recoil system isnt configurable for every weapon, once you enable it, it enables it for every weapon

oh i forgot to say something. when u set X Y to 1.0 it will fuck ur rcs to control it because it instantly change ur view.
