### ISSUE TITLE
Double Tap

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#252]
Just compiled and dt doesnt show in keybinds. Btw disable fake lag when using dt or hs.

**Comment by notgoodusename** [comment]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/Fakelag.cpp#L38
Fakelag adjusts itself when enabling dt or hs

**Comment by notgoodusename** [comment]
> but can you fix it not showing?

done

**Comment by Navoichyk** [comment]
> > but can you fix it not showing?
> 
> done

have you added cristyanuls resolver? its actually pretty decent.

**Comment by Navoichyk** [comment]
> > > > but can you fix it not showing?
> > > 
> > > 
> > > done
> > 
> > 
> > have you added cristyanuls resolver? its actually pretty decent.
> 
> i did to my fork, but i modified some stuff and its very p. but now with dt and 

is your fork the exact same as cristyanuls? or is it just with the updated hs and dt?

**Comment by Navoichyk** [comment]
> > > > > > but can you fix it not showing?
> > > > > 
> > > > > 
> > > > > done
> > > > 
> > > > 
> > > > have you added cristyanuls resolver? its actually pretty decent.
> > > 
> > > 
> > > i did to my fork, but i modified some stuff and its very p. but now with dt and
> > 
> > 
> > is your fork the exact same as cristyanuls? or is it just with the updated hs and dt?
> 
> nah. it has this menu and his resolver. also added roll aa and made it work again.

bro holy shit imma use ur shit. can i get your discord?

**Comment by notgoodusename** [comment]
> have you added cristyanuls resolver? its actually pretty decent.

Imma look into it

**Comment by Navoichyk** [comment]
> > > > > > > > but can you fix it not showing?
> > > > > > > 
> > > > > > > 
> > > > > > > done
> > > > > > 
> > > > > > 
> > > > > > have you added cristyanuls resolver? its actually pretty decent.
> > > > > 
> > > > > 
> > > > > i did to my fork, but i modified some stuff and its very p. but now with dt and
> > > > 
> > > > 
> > > > is your fork the exact same as cristyanuls? or is it just with the updated hs and dt?
> > > 
> > > 
> > > nah. it has this menu and his resolver. also added roll aa and made it work again.
> > 
> > 
> > bro holy shit imma use ur shit. can i get your discord?
> 
> yes but its 3 am and my pc is dead

ah shit ok. later then

**Comment by Navoichyk** [comment]
im hiraeth#1111

> > > > > > > > but can you fix it not showing?
> > > > > > > 
> > > > > > > 
> > > > > > > done
> > > > > > 
> > > > > > 
> > > > > > have you added cristyanuls resolver? its actually pretty decent.
> > > > > 
> > > > > 
> > > > > i did to my fork, but i modified some stuff and its very p. but now with dt and
> > > > 
> > > > 
> > > > is your fork the exact same as cristyanuls? or is it just with the updated hs and dt?
> > > 
> > > 
> > > nah. it has this menu and his resolver. also added roll aa and made it work again.
> > 
> > 
> > bro holy shit imma use ur shit. can i get your discord?
> > Alt drac#7012

im hiraeth#1111
