### ISSUE TITLE
Thirdperson is kinda smooth. Any way to fix?

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#263]

**Comment by notgoodusename** [comment]
What?

**Comment by notgoodusename** [comment]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/Visuals.cpp#L456

**Comment by notgoodusename** [comment]
curDist =static_cast<float>(config->visuals.thirdpersonDistance);
