### ISSUE TITLE
Suggestion | Fake Lag Chams

### ISSUE THREAD

**Issue by Xsintashi** [notgoodusename/OsirisAndExtra#268]
would be nice to see it in cheat.

**Comment by rrhyast** [comment]
> would be nice to see it in cheat.
onetap did this too but what's the point? at the end fake lag animations shows on local player.

**Comment by rrhyast** [comment]
> would be nice to see it in cheat.

onetap did this too but what's the point? at the end fake lag animations shows on local player.

**Comment by Xsintashi** [comment]
> > would be nice to see it in cheat.
> 
> onetap did this too but what's the point? at the end fake lag animations shows on local player.

Always u can check is localPlayer moving
