### ISSUE TITLE
VAC was unable to verify your game session

### ISSUE THREAD

**Issue by 1337Proxy1337** [notgoodusename/OsirisAndExtra#27]
Injector: CSGHOST
Happens when: i go full rage.
it doesn't give any vac errors when i use normal osiris.

**Comment by notgoodusename** [comment]
Do go full rage on casual or only mm?

**Comment by 1337Proxy1337** [comment]
casual

**Comment by RexyAU** [comment]
Do you set max angle delta in the misc section to below 30? If not, you need to for all game modes except mm and wingman because your aimbot is snapping too quickly.

**Comment by Patrixsin** [comment]
set max angle delta to 128 and shouldn't kick you

**Comment by 1337Proxy1337** [comment]
> set max angle delta to 128 and shouldn't kick you

it kicks me if it is 30 <
and it ruins my anti aim

**Comment by Patrixsin** [comment]
Yee, cuz it kicks you beacuz u re i guess spining faster than 30deg per tick. Just use Static AA

**Comment by 1337Proxy1337** [comment]
> Yee, cuz it kicks you beacuz u re i guess spining faster than 30deg per tick. Just use Static AA

yeah. static extended aim = 255 still kicks. guess ill stick to 39 degrees for my static aa and 255 in matchmaking. thanks mate
