### ISSUE TITLE
Killshot Doubletap

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#278]
Better than wasting space for doubletap min damage & hitchance

**Comment by WolfyCSGO** [comment]
shonax technology using hotchance for finding hot pu$$y

**Comment by rrhyast** [comment]
> shonax technology using hotchance for finding hot pu$$y
![hqdefault](https://user-images.githubusercontent.com/62977195/181914939-ecfd4577-815c-44bc-b342-191573cf4e6d.jpg)
