### ISSUE TITLE
Thirdperson not working

### ISSUE THREAD

**Issue by GetRektLOL** [notgoodusename/OsirisAndExtra#28]

**Comment by 1337Proxy1337** [comment]
It isn't working on me neither. it worked fine a day ago and stopped working randomly.

**Comment by Patrixsin** [comment]
CSGO Update broke some things

**Comment by notgoodusename** [comment]
Im on vacation right now, if any of you can update the input class and make a pr i would be grateful

**Comment by ohkriss** [comment]
I will take a closer look at it and fix it
