### ISSUE TITLE
The antivirus reacts strangely to some of the libraries in the cheat i.g Win32/Contebrew.A!ml ( miner )

### ISSUE THREAD

**Issue by unemknip** [notgoodusename/OsirisAndExtra#290]
Hello, my friend wanted to play with your cheat and when you run the cheat, the antivirus does not allow you to do this. On his computer, he ran various cheats, but this only happens with yours. I looked at the source and could not find anything suspicious, but also I did not see any libraries unknown to me, everything that you use uses most coders in cheats. This is very strange could you comment if you have any guesses?

WindowsDefender talking about Win32/Contebrew.A!ml ( miner )

**Comment by notgoodusename** [comment]
A friend of mine had the same problem too, im unsure as to why it happens since i cant replicate it

**Comment by unemknip** [comment]
> A friend of mine had the same problem too, im unsure as to why it happens since i cant replicate it

I asked him to check the regular osiris and no such problem, thanks for the answer anyway. 

As for the cheat, I noticed a couple of bugs, your double tap works fine when you shoot on your own, but with aim it seems to not work or rarely works. You don't need to touch the CanFire function in the aimbot, the correct solution is to add shift ticks to the IsValid (delta time ) check in lag compensation. And your tickbase fix is ​​not quite right, my friend included cl_showerror 2 and when firing sometimes there are strong differences between client and server. In any case, good luck with the development, if I have time I can help you in the future!

**Comment by notgoodusename** [comment]
> As for the cheat, I noticed a couple of bugs, your double tap works fine when you shoot on your own, but with aim it seems to not work or rarely works. You don't need to touch the CanFire function in the aimbot, the correct solution is to add shift ticks to the IsValid (delta time ) check in lag compensation. And your tickbase fix is ​​not quite right, my friend included cl_showerror 2 and when firing sometimes there are strong differences between client and server. In any case, good luck with the development, if I have time I can help you in the future!

tickbase is pure bs, sometimes it misspredicts other times it predicts perfectly, i had to manually add each tick you werent moving in clmove, and still that can go wrong, most of the time it breaks with ping but even then it works fine most of the time
And you are right about the isValid check, im going to fix it later
