### ISSUE TITLE
triggerbot burst fire

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#292]
fucking R8 thinking where to shoot

**Comment by rrhyast** [comment]
https://files.catbox.moe/y5iuqu.m4v

**Comment by notgoodusename** [comment]
If you mean the constant crick sound, the disable prepare revolver

**Comment by rrhyast** [comment]
> If you mean the constant crick sound, the disable prepare revolver

:/ no i didn't mean that.

**Comment by notgoodusename** [comment]
I dont get what is the problem, the video shows the triggerbot working fine

**Comment by rrhyast** [comment]
> I dont get what is the problem, the video shows the triggerbot working fine



> I dont get what is the problem, the video shows the triggerbot working fine

it doesn't shoot fucking head when it had to, burst fire can fix it.
