### ISSUE TITLE
notgoodusername this is for you <3

### ISSUE THREAD

**Issue by Liam5750** [notgoodusename/OsirisAndExtra#3]
Christmas Floppa#8508 please add me on discord <3 I think this would be amazing if you would port all this to the newest Osiris. I am currently attempting at it but it's hard. So maybe I and you could make a new repo dedicated to just porting this to the newest Osiris.

**Comment by notgoodusename** [comment]
I dont think its worth it, since i could just add the features to this repo rather than porting it
Also, the only big difference between this repo and Osiris is the inventory changer

**Comment by diekunstderfuge** [comment]
If you don't mind me saying, I think it is worthy!
Please do it. You could give the project a name of your own, like NEPS, which is also based on Osiris.

**Comment by notgoodusename** [comment]
I can change the name of the proyect at any given time, and porting the whole proyect to a new one would be really tiresome, plus why do that when i could just port the features i need from osiris?

**Comment by twentty-nd** [comment]
This guy wants the Inventory Changer to change this menu and sell it, i'm sure.

**Comment by roscagio** [comment]
> notgoodusername this is for you <3 
his name is notgoodusename
                                          ^ no 'r'
close this issue
