### ISSUE TITLE
silent rcs get broken when using legitbot 

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#314]

**Comment by rrhyast** [comment]
> not broken for me



> not broken for me
ok watch this:
https://streamable.com/sd5b8x

**Comment by rrhyast** [comment]
> > > not broken for me
> > 
> > 
> > ok watch this:
> > https://streamable.com/sd5b8x
> 
> cfg issue bro. Just use regular rcs if you go for legit cheating. Never use silent if you go legit cheat cause i got a prime account banned in 40 days with silent meanwhile with none activated (aim lock and silent) im still not banned after 93 days

bro wtf that's non sense excuse, with bare eyes u can see that weapon (m4a1) supporting silent rcs but instead still using normal rcs. nothing related to the ban.

**Comment by Navoichyk** [comment]
> > > > not broken for me
> > > 
> > > 
> > > ok watch this:
> > > https://streamable.com/sd5b8x
> > 
> > 
> > cfg issue bro. Just use regular rcs if you go for legit cheating. Never use silent if you go legit cheat cause i got a prime account banned in 40 days with silent meanwhile with none activated (aim lock and silent) im still not banned after 93 days
> 
> bro wtf that's non sense excuse, with bare eyes u can see that weapon (m4a1) supporting silent rcs but instead still using normal rcs. nothing related to the ban.

I gotta agree. Silent rcs is completely client sided. It’s only for qol

**Comment by rrhyast** [comment]
> > > > > not broken for me
> > > > 
> > > > 
> > > > ok watch this:
> > > > https://streamable.com/sd5b8x
> > > 
> > > 
> > > cfg issue bro. Just use regular rcs if you go for legit cheating. Never use silent if you go legit cheat cause i got a prime account banned in 40 days with silent meanwhile with none activated (aim lock and silent) im still not banned after 93 days
> > 
> > 
> > bro wtf that's non sense excuse, with bare eyes u can see that weapon (m4a1) supporting silent rcs but instead still using normal rcs. nothing related to the ban.
> 
> I gotta agree. Silent rcs is completely client sided. It’s only for qol

it can be easily fixed just by ignoring normal rcs for weapons that support silent rcs mode.

**Comment by rrhyast** [comment]
Also triggerbot on communtiy servers are detected. it doesn't matter what hitchance or delay you are using. the only good replacement for this problem is magnet (fov makes your first person view shaking too much) and people who spectating u can easily findout you are cheating.

**Comment by notgoodusename** [comment]
Silent RCS is for blatant cheating and should never be used in legit cheating 
I don't know how to bypass the triggerbot it being detected 
Also the "shaking" with aimlock is client sided, although everybody else can easily see you are cheating
