### ISSUE TITLE
[BUG] Thirdperson

### ISSUE THREAD

**Issue by POWERzzzzz** [notgoodusename/OsirisAndExtra#327]
idk if im doing something wrong here but if i activate thirdperson my crosshair is somewhere in the sky and totally detached from first person, like hard to describe but sum ting wong for sure

**Comment by POWERzzzzz** [comment]
and a question: in aimbot below hitchance it says 'distance: 1u' etc. , what does this mean/do

**Comment by notgoodusename** [comment]
Show a screenshot

**Comment by POWERzzzzz** [comment]
![image](https://user-images.githubusercontent.com/24275622/185471719-abad67a1-814e-446b-a0bb-7f6f7eb4fe22.png)

**Comment by notgoodusename** [comment]
That's a different cheat

**Comment by Navoichyk** [comment]
> ![image](https://user-images.githubusercontent.com/24275622/185471719-abad67a1-814e-446b-a0bb-7f6f7eb4fe22.png)

Heyyy question, can you send me that gui. Goddamn that’s nice lmfao

**Comment by notgoodusename** [comment]
> Heyyy question, can you send me that gui. Goddamn that’s nice lmfao

I'm pretty sure it's from a public cheat

**Comment by Navoichyk** [comment]
> > Heyyy question, can you send me that gui. Goddamn that’s nice lmfao
> 
> I'm pretty sure it's from a public cheat

What cheat is that? I thought it was just urs with more features

**Comment by POWERzzzzz** [comment]
well the third person bug still stands

**Comment by Navoichyk** [comment]
> well the third person bug still stands

So ur asking a question about third person from a different cheat?

**Comment by POWERzzzzz** [comment]
no its in this too!

**Comment by Navoichyk** [comment]
> no its in this too!

What source are you using?

**Comment by POWERzzzzz** [comment]
NEPS

**Comment by Navoichyk** [comment]
> NEPS

The paid version? I don’t remember Nepal’s having all that

**Comment by POWERzzzzz** [comment]
Not paid

**Comment by notgoodusename** [comment]
> What cheat is that? I thought it was just urs with more features

It's NEPS, search it up

**Comment by Navoichyk** [comment]
> Not paid

Wow

**Comment by Navoichyk** [comment]
> Not paid

Can I add you on disc?

**Comment by notgoodusename** [comment]
> no its in this too!

It isn't because it's obvious that you haven't used it

**Comment by notgoodusename** [comment]
> Can I add you on disc? 

It literally is open source

**Comment by Navoichyk** [comment]
@POWERzzzzz why aren’t you asking these questions where the cheat originated from?

**Comment by Navoichyk** [comment]
> > Can I add you on disc?
> 
> It literally is open source

I know

**Comment by POWERzzzzz** [comment]
im sorry i mixed it up

**Comment by POWERzzzzz** [comment]
Riot#5437
