### ISSUE TITLE
Random crash (call stack included)

### ISSUE THREAD

**Issue by codecheck01** [notgoodusename/OsirisAndExtra#342]
![Untitled](https://user-images.githubusercontent.com/98359300/188328338-b61690c0-8fac-4083-b08f-e5032a44c49a.png)

https://github.com/notgoodusename/OsirisAndExtra/blob/c863bbfac5c923f9796399ae2e6ec60ae0339466/Osiris/Hacks/Visuals.cpp#L142-L148
`molotovs.erase(molotovs.begin()); <--- CRASHING HERE`

**Comment by propane** [comment]
Do you have a discord?

**Comment by notgoodusename** [comment]
Add an if statement
if molotovs are empty return

**Comment by codecheck01** [comment]
@notgoodusename fixed it. (commit https://github.com/notgoodusename/OsirisAndExtra/commit/cf943c4ef1a1490a121f1b9434770fde4b87d5a4)
