### ISSUE TITLE
How can i make it load a config on start 

### ISSUE THREAD

**Issue by Fearqueesha** [notgoodusename/OsirisAndExtra#351]

**Comment by Navoichyk** [comment]
ohhh this would be cool! like whatever config you last loaded before closing csgo; when you first inject again it’ll load that cfg?

**Comment by Xsintashi** [comment]
`config->load(u8"*config name*", false);` at [here](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hooks.cpp#L86)
