### ISSUE TITLE
Does anybody have a Resolver + Roll AA for the newest BetterOsiris update?

### ISSUE THREAD

**Issue by Synth1a** [notgoodusename/OsirisAndExtra#358]
I tried importing cristyanul's one, but failed. Can anybody help me?

**Comment by Navoichyk** [comment]
cristyanuls doesnt really work

**Comment by Synth1a** [comment]
It works on his fork, which is quite old as of now

**Comment by Synth1a** [comment]
> cristyanuls doesnt really work

It works on his fork, which is quite old as of now
