### ISSUE TITLE
Keybind List position wont save

### ISSUE THREAD

**Issue by BaluxX** [notgoodusename/OsirisAndExtra#359]
I don't know if this is an error that often occurs, but my keybind list wont saved after saving my cfg

**Comment by Xsintashi** [comment]
do u mean position?

**Comment by BaluxX** [comment]
yes sorry

**Comment by Xsintashi** [comment]
they should work cuz of https://github.com/notgoodusename/OsirisAndExtra/issues/355
sometimes they may just reset their pos or something
