### ISSUE TITLE
Lua API

### ISSUE THREAD

**Issue by gr1ndy** [notgoodusename/OsirisAndExtra#363]
cant seem to find a way to make pulls on phone, but regarding the title, heres a somewhat "old" osiris mod that u can take the api from

https://github.com/TXIuTnVsbA/Osiris_Edit

**Comment by Navoichyk** [comment]
> cant seem to find a way to make pulls on phone, but regarding the title, heres a somewhat "old" osiris mod that u can take the api from
> 
> https://github.com/TXIuTnVsbA/Osiris_Edit

i think adding lw lua api would be amazing because it’s already set up and there are already plenty of luas made for that api

**Comment by Navoichyk** [comment]
> > > cant seem to find a way to make pulls on phone, but regarding the title, heres a somewhat "old" osiris mod that u can take the api from
> > > https://github.com/TXIuTnVsbA/Osiris_Edit
> > 
> > 
> > i think adding lw lua api would be amazing because it’s already set up and there are already plenty of luas made for that api
> 
> lw api its just so dogshit, not rlly worth

okay then some other api that is already set up and shit so it’s not starting from scratch.

**Comment by gr1ndy** [comment]
> > > > cant seem to find a way to make pulls on phone, but regarding the title, heres a somewhat "old" osiris mod that u can take the api from
> > > > https://github.com/TXIuTnVsbA/Osiris_Edit
> > > 
> > > 
> > > i think adding lw lua api would be amazing because it’s already set up and there are already plenty of luas made for that api
> > 
> > lw api its just so dogshit, not rlly worth
> 
> okay then some other api that is already set up and shit so it’s not starting from scratch. 

what i linked is already good enough. look thru scripting.cpp

**Comment by BlueCat-Frisk** [comment]
I think it is meaningless to use Lua in open source cheat. of course, unless you want to sell :)
Also, it is better to use LuaJIT

**Comment by notgoodusename** [comment]
> I think it is meaningless to use Lua in open source cheat. of course, unless you want to sell :)

this exactly, if the cheat werent open source this issue would make sense, otherwise this is to make a p2c paste of this repo
