### ISSUE TITLE
Animation bugs on Valve servers

### ISSUE THREAD

**Issue by codecheck01** [notgoodusename/OsirisAndExtra#366]
Hello,

On localplayer:

- When you jump with either weapon or knife only, the jump animation is not the same (it should never change), sometime it is normal, sometime it looks like the legs are forward.
- When you land on the ground, the timing is way too fast and not accurate.

@notgoodusename After testing, it only happens on **Valve servers**, _everything_ is fine on local server.

**Comment by notgoodusename** [comment]
What do you mean by "timing way to fast"

**Comment by notgoodusename** [comment]
Yeah it happens to me and I don't really know how to fix it

**Comment by notgoodusename** [comment]
Fixed
