### ISSUE TITLE
still getting pattern 98 error

### ISSUE THREAD

**Issue by Navoichyk** [notgoodusename/OsirisAndExtra#381]

**Comment by KamileK2782** [comment]
What is isUsingStaticPropDebugModes?

**Comment by notgoodusename** [comment]
We don't need this many issues about pattern errors
I'm unable to fix it right now due to personal stuff

**Comment by Navoichyk** [comment]
> We don't need this many issues about pattern errors I'm unable to fix it right now due to personal stuff

okay
