### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gamesenseltdbase** [notgoodusename/OsirisAndExtra#385]
crashing pattern 93 or 94

**Comment by gamesenseltdbase** [comment]
or idk what pattern i have added stuff to it its just crashing

**Comment by Liam5750** [comment]
something to do with findHudElement. I'm working on it rn

**Comment by Liam5750** [comment]
also make sure you've updated your lookUpBone signature or that you have downloaded the most recent build of the software.

**Comment by BlueCat-Frisk** [comment]
> something to do with findHudElement. I'm working on it rn

The crash problem lies in clMsgMove
findHudElement does not need to be updated

**Comment by Liam5750** [comment]
> > something to do with findHudElement. I'm working on it rn
> 
> The crash problem lies in clMsgMove(clMsgMoveDescontructor) findHudElement does not need to be updated

I just realized that as I have the iq of a toed-eyed cabbage. No idea how one updates the offsets. If I knew I would update it.

**Comment by gamesenseltdbase** [comment]
@JannesBonk 204

**Comment by gamesenseltdbase** [comment]
line
