### ISSUE TITLE
cant find memory pattern for #91

### ISSUE THREAD

**Issue by 144-lines** [notgoodusename/OsirisAndExtra#386]
i have no idea how to fix it

**Comment by gr1ndy** [comment]
count till pattern 91 and send it

**Comment by gr1ndy** [comment]
if thats ur 91st pattern in memory.cpp.

**Comment by 144-lines** [comment]
by 91 do i have to count them if so then this is my 91st pattern

chokeLimit = findPattern(ENGINE_DLL, "\xB8????\x3B\xF0\x0F\x4F\xF0\x89\x5D\xFC") + 1;

**Comment by 144-lines** [comment]
ill try it

**Comment by 144-lines** [comment]
91 is 

studioSetPoseParameter = relativeToAbsolute<decltype(studioSetPoseParameter)>(findPattern(CLIENT_DLL, "\xE8????\x0F\x28\xD8\x83\xC4\x04") + 1);

**Comment by 144-lines** [comment]
> if thats ur 91st pattern in memory.cpp.

studioSetPoseParameter = relativeToAbsolute<decltype(studioSetPoseParameter)>(findPattern(CLIENT_DLL, "\xE8????\x0F\x28\xD8\x83\xC4\x04") + 1);

**Comment by gr1ndy** [comment]
> studioSetPoseParameter

`float C_BaseAnimating::SetPoseParameter(int,float) from pdb
client.dll -> "55 8B EC 56 8B F1 83 ? ? ? ? ? ? 75 14 8B 46 04 8D 4E 04 FF 50 20 85 C0 74 07 8B CE E8 ? ? ? ? 8B ? ? ? ? ? 85 C0"`

**Comment by gr1ndy** [comment]
if that doesnt work try this one `void CMergedMDL::SetPoseParameters() from partial pdb
client.dll -> "55 8B EC 81 ? ? ? ? ? 8B 45 08 53 8B D9 89 5D FC 85"`

**Comment by 144-lines** [comment]
> if that doesnt work try this one `void CMergedMDL::SetPoseParameters() from partial pdb client.dll -> "55 8B EC 81 ? ? ? ? ? 8B 45 08 53 8B D9 89 5D FC 8

didnt work

**Comment by gr1ndy** [comment]
> > if that doesnt work try this one `void CMergedMDL::SetPoseParameters() from partial pdb client.dll -> "55 8B EC 81 ? ? ? ? ? 8B 45 08 53 8B D9 89 5D FC 8
> 
> didnt work

none of them?

**Comment by 144-lines** [comment]
> > > if that doesnt work try this one `void CMergedMDL::SetPoseParameters() from partial pdb client.dll -> "55 8B EC 81 ? ? ? ? ? 8B 45 08 53 8B D9 89 5D FC 8
> > 
> > 
> > didnt work
> 
> none of them?

both didnt work

**Comment by gr1ndy** [comment]
> > > > if that doesnt work try this one `void CMergedMDL::SetPoseParameters() from partial pdb client.dll -> "55 8B EC 81 ? ? ? ? ? 8B 45 08 53 8B D9 89 5D FC 8
> > > 
> > > 
> > > didnt work
> > 
> > 
> > none of them?
> 
> both didnt work

weird..
