### ISSUE TITLE
Fix pattern #94

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#387]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Memory.cpp line 204
@notgoodusename can u?

**Comment by DLdota** [comment]
clMsgMoveDescontructor = relativeToAbsolute<decltype(clMsgMoveDescontructor)>(findPattern(ENGINE_DLL, "\xFF\x90????\x8D\x4D\xA8\xE8????\x5F\x5E\x5B\x8B\xE5\x5D\xC3") + 10);

**Comment by Xsintashi** [comment]
> > clMsgMoveDescontructor = relativeToAbsolute<decltype(clMsgMoveDescontructor)>(findPattern(ENGINE_DLL, "\xFF\x90????\x8D\x4D\xA8\xE8????\x5F\x5E\x5B\x8B\xE5\x5D\xC3") + 10);
> 
> ill test rn and then ill make a pr

seems to be working

**Comment by Spamm00r** [comment]
ENGINE_DLL, "\xFF\x90????\x8D\x4D\xA8\xE8????\x5F\x5E\x5B\x8B\xE5\x5D\xC3") + 10)

**Comment by Navoichyk** [comment]
> > > > clMsgMoveDescontructor = relativeToAbsolute<decltype(clMsgMoveDescontructor)>(findPattern(ENGINE_DLL, "\xFF\x90????\x8D\x4D\xA8\xE8????\x5F\x5E\x5B\x8B\xE5\x5D\xC3") + 10);
> > > 
> > > 
> > > ill test rn and then ill make a pr
> > 
> > 
> > seems to be working
> 
> https://streamable.com/8x38yh after adding that memory pattern this is what happend to my cheeto

the like feathers?
