### ISSUE TITLE
Problem with voice

### ISSUE THREAD

**Issue by KoiHooks** [notgoodusename/OsirisAndExtra#395]
Whenever I am injected and move my mouse while talking the voice lags and makes other sounds

**Comment by Xsintashi** [comment]
Only what could cause that is fakelag set more than 2 afaik

**Comment by KoiHooks** [comment]
> Only what could cause that is fakelag set more than 2 afaik

> it doesnt lag, you will just hear those client side sounds, thats it

fixed it, it was a problem with the cl_sendmove hook

**Comment by Navoichyk** [comment]
> > Only what could cause that is fakelag set more than 2 afaik
> 
> > it doesnt lag, you will just hear those client side sounds, thats it
> 
> fixed it, it was a problem with the cl_sendmove hook

what did you do to solve this?

**Comment by KoiHooks** [comment]
> > > Only what could cause that is fakelag set more than 2 afaik
> > 
> > 
> > > it doesnt lag, you will just hear those client side sounds, thats it
> > 
> > 
> > fixed it, it was a problem with the cl_sendmove hook
> 
> what did you do to solve this?

At the moment I just removed the hook, I'll be implementing a fix when I find one

**Comment by Navoichyk** [comment]
> > > > Only what could cause that is fakelag set more than 2 afaik
> > > 
> > > 
> > > > it doesnt lag, you will just hear those client side sounds, thats it
> > > 
> > > 
> > > fixed it, it was a problem with the cl_sendmove hook
> > 
> > 
> > what did you do to solve this?
> 
> At the moment I just removed the hook, I'll be implementing a fix when I find one

oh so removing it fixes it?

**Comment by Navoichyk** [comment]
> > > > Only what could cause that is fakelag set more than 2 afaik
> > > 
> > > 
> > > > it doesnt lag, you will just hear those client side sounds, thats it
> > > 
> > > 
> > > fixed it, it was a problem with the cl_sendmove hook
> > 
> > 
> > what did you do to solve this?
> 
> its in neps source, just paste

which one is clsendmove in neps? I added movedata bc its the only thing that seemed similar and it doesnt work. Gives a pattern 90 error.

**Comment by Coder-Random** [comment]
Anyone found a fix for this?

**Comment by Xsintashi** [comment]
https://github.com/notgoodusename/OsirisAndExtra/pull/524

**Comment by Coder-Random** [comment]
Yeah that doesnt fix anything it isnt a fakelag issue. It only happens when you move the mouse while talking in game. It has to do with clSendMoveHook() but i dont know what  the issue is and if i remove the whole hook i cant move at all in game.
