### ISSUE TITLE
Auto shot should shoot through penetrable walls! (autowall)

### ISSUE THREAD

**Issue by diekunstderfuge** [notgoodusename/OsirisAndExtra#4]
This hack is good, but it has the same problem that Osiris: It needs autowall.

Without it it doesn't stand a chance against other mediocre ragebots that have autowall.

**Comment by notgoodusename** [comment]
Disable visible only, and it autowalls

**Comment by notgoodusename** [comment]
Heres a video of the autowall working fine
https://streamable.com/31xrzr

**Comment by diekunstderfuge** [comment]
> Disable visible only, and it autowalls

Hey, now it is working! It wasn't working before!
Thanks anyway! Now your hack is my favorite hack!
