### ISSUE TITLE
Resolver Was there before but its removed now??

### ISSUE THREAD

**Issue by GetRektLOL** [notgoodusename/OsirisAndExtra#40]
https://github.com/notgoodusename/osiriswithstuff/blob/master/Osiris/Hacks/Resolver.cpp . A resolver was there before in osiriswithstuff, any reason it was removed?

**Comment by notgoodusename** [comment]
That resolver is overcomplicated and performance expensive, basically you run auto wall for every shot you fire

**Comment by GetRektLOL** [comment]
oh well, thats not really efficient, so yeah thanks anyway
