### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by meth1337** [notgoodusename/OsirisAndExtra#405]
as original osiris supports linux, is it possible to do it for this paste?

**Comment by Xsintashi** [comment]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/README.md?plain=1#L5

**Comment by meth1337** [comment]
> https://github.com/notgoodusename/OsirisAndExtra/blob/main/README.md?plain=1#L5

"no" means that there is currently no support for linux, but it may be developed in one or other way

**Comment by meth1337** [comment]
> > as original osiris supports linux, is it possible to do it for this paste?
> 
> it is, but its hard, i am still working on that, currently got only menu injection and nothing else

are you doing it yourself?

**Comment by notgoodusename** [comment]
no means no, there won't be development for one

**Comment by meth1337** [comment]
> > > > as original osiris supports linux, is it possible to do it for this paste?
> > > 
> > > 
> > > it is, but its hard, i am still working on that, currently got only menu injection and nothing else
> > 
> > 
> > are you doing it yourself?
> 
> ye

maybe i can help u with it, as soon as it will be done we may make a fork and create a pull request for creator to merge it

**Comment by Xsintashi** [comment]
if u have free time and want to spend many days of looking for memory signs and pads, go ahead
