### ISSUE TITLE
Kicks

### ISSUE THREAD

**Issue by recalltang** [notgoodusename/OsirisAndExtra#41]
how about fix valve servers random kick

**Comment by recalltang** [comment]
i just try the new update but its still kick my by the reason of connect error

**Comment by recalltang** [comment]
and i got redownload the game and play without cheats. it doesnt kick me (around 1.5h game played)

**Comment by recalltang** [comment]
and i tried not redownload the game after kick and unhook cheats, it still connect error, so i redownload the game. and then the error doesnt come out

**Comment by recalltang** [comment]
btw idk if its the cheat's bug

**Comment by Patrixsin** [comment]
I discovered or only my cheats does this, but when i inject my cheat to game while playing / joining to server, server crasher
