### ISSUE TITLE
Menu Size

### ISSUE THREAD

**Issue by xomarko** [notgoodusename/OsirisAndExtra#411]
How do i change the size of the menu so that everything fits?

**Comment by Xsintashi** [comment]
https://github.com/notgoodusename/OsirisAndExtra/issues/347

**Comment by xomarko** [comment]
> #347

![image](https://user-images.githubusercontent.com/115811042/202723498-ce3648d4-9ee3-4e66-aa79-2b47b613b07f.png)
looks like this lol

**Comment by Xsintashi** [comment]
> > #347
> 
> looks like this lol

I recommend read whole thread than only one message
