### ISSUE TITLE
question

### ISSUE THREAD

**Issue by T4lk** [notgoodusename/OsirisAndExtra#421]
is there somekind of protection so u don't go over viewangles.x = -+89.f?
trying to do some janky fake pitches w roll seems like fake pitch doesn't work

**Comment by simv0lofficial** [comment]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/SDK/Vector.h#L150
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hooks.cpp#L416

**Comment by T4lk** [comment]
thank you
