### ISSUE TITLE
RageBot: Autowall Request (NOT A ISSUE)

### ISSUE THREAD

**Issue by CrenixOfficial** [notgoodusename/OsirisAndExtra#422]
Add autowall it will make the cheat much better for hvh.

**Comment by CrenixOfficial** [comment]
Yes but its ass

**Comment by simv0lofficial** [comment]
> > nahh it's a request dumbass
> 
> whell, u see, if u want a request, just do it urself, make pr and add auto wall. Anyway, learncpp.com

![image](https://user-images.githubusercontent.com/53585642/206764584-7551101a-f767-45d1-8088-922ca4cad3f3.png)
learncsgosdk.com and stop write shit here

**Comment by notgoodusename** [comment]
The auto wall functions exactly the same as your favorite p2c, so no, there won't be a need for an update, and just because it's open source it doesn't mean it's bad or trash
