### ISSUE TITLE
[Little-Anti-Cheat] Name Newlines Detected

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#427]
I tried to join a server with LAC with different accounts & different names but all of them got banned for a stupid reason. Don't even know what cause it to happen but I'm pretty sure it's not on steam config files cause. I remember I used to change my name with name changer then after map change that happen. 

here's some reference to the issue but I didn't understand it so i share it here:
https://github.com/J-Tanzanite/Little-Anti-Cheat/search?q=name+newlines
![csgo_KFI6spvZe5](https://user-images.githubusercontent.com/62977195/207329357-6994d91c-9fe7-4516-99bb-0dc13f663b88.jpg)

**Comment by Xsintashi** [comment]
did u use custom name?

**Comment by rrhyast** [comment]
> did u use custom nickname/clantag?

only name changer. custom clantags are safe.

**Comment by Xsintashi** [comment]
i guess ur ip banned

**Comment by rrhyast** [comment]
> i guess ur ip banned

nah my IP is dynamic, I restarted my modem couple times for that. I think i have to reinstall cs go, it might help.

**Comment by notgoodusename** [comment]
u are ip banned
