### ISSUE TITLE
What osiris base is this on

### ISSUE THREAD

**Issue by yEsPaP** [notgoodusename/OsirisAndExtra#43]
what version of osiris tree is this based on?

wanna merge it to main, mostly for invchanger stuff, so would be good to know. thx.

**Comment by yEsPaP** [comment]
i tried searching, it looks like https://github.com/danielkrupinski/Osiris/tree/2ff8055570cf933b7cba3324af2635942f072e86 with linux stuff removed.

**Comment by notgoodusename** [comment]
i know its osiris but i cant remember the date

**Comment by yEsPaP** [comment]
> i know its osiris but i cant remember the date

lol

**Comment by yEsPaP** [comment]
> i know its osiris but i cant remember the date

i was looking into some files to see, and i see there is https://github.com/danielkrupinski/Osiris/commit/ddaf08f0379a65fd360461fda154564c296f5707 applied , but some before that are missing

**Comment by yEsPaP** [comment]
> i know its osiris but i cant remember the date

ok i managed to rebase it on latest one

everything works except keybinds
zzzzzzzzzz

**Comment by notgoodusename** [comment]
Look into this [commit](https://github.com/notgoodusename/OsirisAndExtra/commit/f7483867c94f70bc374417bc3ba7562a742125e6)

**Comment by yEsPaP** [comment]
> Look into this [commit](https://github.com/notgoodusename/OsirisAndExtra/commit/f7483867c94f70bc374417bc3ba7562a742125e6)

i did. it kinda doesnt work idk

maybe because of this https://github.com/danielkrupinski/Osiris/commit/0f0b1d8df4f249dc3283be3efe3fd3c7ffc27fad

**Comment by yEsPaP** [comment]
> Look into this [commit](https://github.com/notgoodusename/OsirisAndExtra/commit/f7483867c94f70bc374417bc3ba7562a742125e6)

nvm it was actually working, i just tested it on triggerbot and i havent set hit groups then. it all works
also idk why but with this cheat movement of others is kinda weird. sometimes they move like crab
