### ISSUE TITLE
Head scale and body scale

### ISSUE THREAD

**Issue by CrenixOfficial** [notgoodusename/OsirisAndExtra#440]
Could be fire if you added head scale and body scale!

**Comment by CrenixOfficial** [comment]
> medusa.uno

Whats  that?

**Comment by notgoodusename** [comment]
> Could be fire if you added head scale and body scale!

there's already a global scale (it's for both head and body), it's called multipoint

**Comment by CrenixOfficial** [comment]
could you maybe show me how i make em not global?

**Comment by notgoodusename** [comment]
I could but you do realize that making it 2 separate values is basically pointless, right?

**Comment by CrenixOfficial** [comment]
> I could but you do realize that making it 2 separate values is basically pointless, right?

yea but like, idk it just looks better for me.

**Comment by CrenixOfficial** [comment]
> > > I could but you do realize that making it 2 separate values is basically pointless, right?
> > 
> > 
> > yea but like, idk it just looks better for me.
> 
> useless feature, i added it to my paste and nothing differs

okay?
