### ISSUE TITLE
When i use the clantag it lags like crazy

### ISSUE THREAD

**Issue by CrenixOfficial** [notgoodusename/OsirisAndExtra#443]

**Comment by Xsintashi** [comment]
clantag updates to quickly then

**Comment by CrenixOfficial** [comment]
> clantag updates too quickly then

How do i fix?

My code:
        static float lastTime = 0.0f;
        float currentTime = memory->globalVars->currenttime * 1.0f;

        if (lastTime != currentTime)
        {
            std::string buf = ClanTags[(int)currentTime % ClanTags.size()];
            memory->setClanTag(buf.c_str(), buf.c_str());
            lastTime = currentTime;
        }

**Comment by Xsintashi** [comment]
basically u multiply currenttime by 1, making it still the same value. 

```c++
static float lastTime = 0.0f;

if (memory.globalVars->realtime - lastTime < 0.6f)
    return;
    
//ur clantag code

lastTime = memory.globalVars->realtime;
```
