### ISSUE TITLE
Crash fix

### ISSUE THREAD

**Issue by CrenixOfficial** [notgoodusename/OsirisAndExtra#444]

**Comment by CrenixOfficial** [comment]
everytime i open the buy menu it crashes i think it's because of the skin changer but im not sure.

**Comment by Xsintashi** [comment]
pls use debugger to be more precised

**Comment by CrenixOfficial** [comment]
> > everytime i open the buy menu it crashes i think it's because of the skin changer but im not sure.
> 
> please give context

when i open the buy menu in game it sometimes just crashes it says some about "Imgui_draw" or something like that

**Comment by dapaster** [comment]
screenshot?

**Comment by Xsintashi** [comment]
Bro doesnt know what he is doing, like I bet he uses the cheat in debug mode to normal play

**Comment by CrenixOfficial** [comment]
> Bro doesnt know what he is doing, like I bet he uses the cheat in debug mode to normal play

no i dont i use release?
