### ISSUE TITLE
Need help with sticker changer

### ISSUE THREAD

**Issue by CrenixOfficial** [notgoodusename/OsirisAndExtra#447]
![image](https://user-images.githubusercontent.com/80490892/208979862-473b65b8-85ee-4ab6-bf5e-826a3c5bd1d6.png)
![image](https://user-images.githubusercontent.com/80490892/208979896-28e44bbc-4db9-4320-841b-eaf3a97c364e.png)

**Comment by CrenixOfficial** [comment]
how can i fix this?

**Comment by Xsintashi** [comment]
give more info or https://learncpp.com

**Comment by CrenixOfficial** [comment]
> give more info or https://learncpp.com

I have tried to make a sticker window but it gives a error i have tried to look on the internet and it dont help

**Comment by Xsintashi** [comment]
You can't send more code, so I guess you wants to use variable in lambda(function in function) but you cannot do that.

**Comment by CrenixOfficial** [comment]
> You can't send more code, so I guess you wants to use variable in lambda(function in function) but you cannot do that.

i fixed it
