### ISSUE TITLE
Prediction class issue

### ISSUE THREAD

**Issue by codecheck01** [notgoodusename/OsirisAndExtra#459]
https://github.com/notgoodusename/OsirisAndExtra/blob/c302f2a8342fcc2a5584723d96cbd41ebf554e44/Osiris/SDK/Prediction.h#L11-L18

@notgoodusename We have reversed it in IDA, I am pretty sure you inverted two variables. (incorrect order)

**Comment by notgoodusename** [comment]
Could you post the correct struct for this pls?

**Comment by Navoichyk** [comment]
if it’s incorrect, how can it return correct values? that doesn’t make any sense.

**Comment by notgoodusename** [comment]
@codecheck01 is correct
