### ISSUE TITLE
butterfly and some knifes lagging in valve servers

### ISSUE THREAD

**Issue by recai-m** [notgoodusename/OsirisAndExtra#461]
Hello, im using skin changer to change my knife but in offical matchmaking the knife lagging like trying to do 2 animation in same time.
Anyone know how to fix this?

**Comment by St0rmmx** [comment]
skill issue ngl

**Comment by rrhyast** [comment]
> Hello, im using skin changer to change my knife but in offical matchmaking the knife lagging like trying to do 2 animation in same time. Anyone know how to fix this?

ping issue

**Comment by recai-m** [comment]
> > Hello, im using skin changer to change my knife but in offical matchmaking the knife lagging like trying to do 2 animation in same time. Anyone know how to fix this?
> 
> ping issue

I genuinely have 50 ms. Is it the issue?

**Comment by BokoneNanePHN7OM** [comment]
@rrhyast اره داداش مامانت پینگش پایینه کیرم تو ناموست سبحان بهنامی بیناموس مادرجنده خارکصه ننه کیر دزد کیرم تو جد ابادت

زنتو گاییدم تف تو قبر کص ننت

دعا کن شمارتو پخش نکنم اسم خاندانتو از رویه شمارت استعلام نگیرم پخش کنم کیرم به هفت جد اباد ننه کصه هزار پرد خارکصه

برو دنبال یه اسم جدید بگیرد حرومزاده تو روبه نابودی هستی پسرم خیارمو بیارم بدم دستت تو تهران کیرم تو پاساژ عمو کصکشت

فکر کردی بعد از 2 سال دیگه کسی یادش نیست چقدر کیر خوردی از تیم ما؟ ننتو یجوری میگاییم با دکتر چیت که نفهمی از کجا خوردی بیناموس برو اکانت گیت هابتو دلیت کن تا وضعت خراب تر از این نشده

بعدشم مادرجنده تو کی باشی بخوای توییتر نصب کنی کیرم تو مغزت و سطح نداشتت که درباره چیزی که اطلاع نداری پست میزاری مهسا امینی و کیر خر تو کص مادرت
X)
حالا دیگه تو کاری که توش تخصص نداری گوه اضافه نخور که یجوری ننتو میگام که عموی کصکشت تویه مغازه تک پاب هم نتونه تورو از رویه کیر بسیجیا دراره

ما مراقبتیم حواست به ناموست باشه که یوقت نگاییمش 3 ساله زیر نظرمونی
#آنقدر_بزرگ_هستیم_که_تورا_زمین_بزنیم
حالا هرییییی مادرکصه
#Owned_PHN7OM
#Owned_Sobhan_Behnami
#Owned_Rrhyast
#Owned_Hit

**Comment by Wolfyyta** [comment]
never got this even with 130 ping. are you using the default version of this?
