### ISSUE TITLE
Error on inject ( pls help me ;( )

### ISSUE THREAD

**Issue by SkKrT1** [notgoodusename/OsirisAndExtra#463]
All the errors are :
faild to find pattern #8
faild to find pattern #63
faild to find pattern #65

pls help me ;(

**Comment by SkKrT1** [comment]
> 

how do i update patterns i know im noob but everyone has to learn som how :)

**Comment by dapaster** [comment]
> > 
> 
> how do i update patterns i know im noob but everyone has to learn som how :)

IDA

**Comment by Wolfyyta** [comment]
the source works fine. check what you pasted of the internet
