### ISSUE TITLE
What is the bypass?

### ISSUE THREAD

**Issue by DNTtianci666** [notgoodusename/OsirisAndExtra#471]
Is this a version with its own VAC bypass or a version with a legal bypass or a version without a bypass?

**Comment by DNTtianci666** [comment]
> 💀

Does this dll have a bypass? If the bypass is automatic, is this bypass VAC bypass or a legal bypass?

**Comment by Xsintashi** [comment]
no bypass

**Comment by SightDev** [comment]
+ Can you go into more detail on what you mean by "legal bypass"?

**Comment by DNTtianci666** [comment]
> 无旁路

I need to load a bypass injector to get in, right?

**Comment by notgoodusename** [comment]
there is no injector in this repo as such there is no "bypass"
