### ISSUE TITLE
Where can I contact you?

### ISSUE THREAD

**Issue by wirekuro** [notgoodusename/OsirisAndExtra#474]
@notgoodusename

**Comment by wirekuro** [comment]
I need help fixing extended backtrack for current osiris.

**Comment by notgoodusename** [comment]
> I need help fixing extended backtrack for current osiris.

havent quite figured that one out tbh, high fakelatency + backtrack ragebot misses a lot

**Comment by wirekuro** [comment]
> > I need help fixing extended backtrack for current osiris.
> 
> havent quite figured that one out tbh, high fakelatency + backtrack ragebot misses a lot

I meant danielkrupinski's current osiris.

**Comment by Xsintashi** [comment]
> > I need help fixing extended backtrack for current osiris.
> 
> havent quite figured that one out tbh, high fakelatency + backtrack ragebot misses a lot

even without aimbot  often misses

**Comment by notgoodusename** [comment]
> even without aimbot  often misses

I think that's your aim, legit backtracking works fine

**Comment by notgoodusename** [comment]
> I meant danielkrupinski's current osiris.

can't do, new osiris code style is shit and i don't even want to touch it

**Comment by Xsintashi** [comment]
> > even without aimbot  often misses
> 
> I think that's your aim, legit backtracking works fine

![image](https://user-images.githubusercontent.com/61426269/212425909-3243d136-98ab-41f2-aca9-aca374152bd2.png)
think so, or i just pasted it badly, whatever

**Comment by notgoodusename** [comment]
> > > even without aimbot  often misses
> > 
> > I think that's your aim, legit backtracking works fine
> 
> ![image](https://user-images.githubusercontent.com/61426269/212425909-3243d136-98ab-41f2-aca9-aca374152bd2.png)
> think so, or i just pasted it badly, whatever

idk what you want me to tell you it's the same backtracking code from every other source ever, literally the only difference is that there are more points to calc distance instead of only origin

**Comment by Xsintashi** [comment]
> > > > even without aimbot  often misses
> > > 
> > > 
> > > I think that's your aim, legit backtracking works fine
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61426269/212425909-3243d136-98ab-41f2-aca9-aca374152bd2.png)
> > think so, or i just pasted it badly, whatever
> 
> idk what you want me to tell you it's the same backtracking code from every other source ever, literally the only difference is that there are more points to calc distance instead of only origin

don't mind, i prob fricked out in code.

**Comment by Xsintashi** [comment]
> > even without aimbot  often misses
> 
> I think that's your aim, legit backtracking works fine

i hadnt updated setupbones cuz it didn't work
