### ISSUE TITLE
emulate mouse (mostly for triggerbot)

### ISSUE THREAD

**Issue by deathruned** [notgoodusename/OsirisAndExtra#483]
Fast stop isn't fast as force stop, also autostop doesn't work without ragebot fully enabled unlike doubletap etc. / emulating mouse helps to aimbot & triggerbot being less detectable by anti cheats like lilac (little anti cheat)

**Comment by deathruned** [comment]
> > Fast stop isn't fast as force stop, also autostop doesn't work without ragebot fully enabled unlike doubletap etc. / emulating mouse helps to aimbot & triggerbot being less detectable by anti cheats like lilac (little anti cheat)
> 
> bro what. `doesn't work without ragebot fully enabled unlike doubletap etc` 💀

Instead of being funny joker read it carefully, doubletap works even ragebot isn't enabled; autostop doesn't contain that certain feature. so why don't add something that works faster than auto stop for legitbot.

**Comment by Xsintashi** [comment]
fast stop and force stop are the same coded thing. About force stop on key, u can just use ragebot on key for that with turned fov to 0 and disabled auto shot

**Comment by deathruned** [comment]
Every possible way for using autostop on legitbot is absolute dogshit, so let's focus on emulating mouse option.

**Comment by Wolfyyta** [comment]
@JannesBonk nl cant even hit a static low delta so what we on here? to sell medusa for 19.99$ per 30 days x)

**Comment by notgoodusename** [comment]
> nl cant even hit a static low delta so what we on here? to sell medusa for 19.99$ per 30 days x)

Medusa is literally free and you prefer to put it behind a paywall? smh
