### ISSUE TITLE
Can't close cheat menu if u inject with opened chat in game.

### ISSUE THREAD

**Issue by Xsintashi** [notgoodusename/OsirisAndExtra#489]
This forces user to reinject, with closed chat in game

**Comment by Liam5750** [comment]
Why would anyone inject with the menu open?

**Comment by Xsintashi** [comment]
> Why would anyone inject with the chat open? Edit: changed menu to chat.

idk, but i do when debugging or testing some features

**Comment by notgoodusename** [comment]
Fixed
