### ISSUE TITLE
purpose of inv unlocker?

### ISSUE THREAD

**Issue by yEsPaP** [notgoodusename/OsirisAndExtra#49]
if you enable and try change lets say from m4a4 to m4a1-s

it shows m4a1-s icon, and then buy it, it will still buy m4a4
it doesnt work

**Comment by linuxer9** [comment]
it works but after the round so the server registers new weapon, it's real purpose if you have inventory changer though...

**Comment by Patrixsin** [comment]
Weapon Loadout always changes before first round and after team switch
