### ISSUE TITLE
Help with resolver

### ISSUE THREAD

**Issue by StephenIsTaken** [notgoodusename/OsirisAndExtra#491]
Hello. I am new to creating cheats and I was wondering if someone would be nice enough to send me a resolver source code and teach me how to implement it. Thanks in advance <3

**Comment by StephenIsTaken** [comment]
> 

Imense thanks !

**Comment by StephenIsTaken** [comment]
> 

Imense thanks !

**Comment by Liam5750** [comment]
I actually have a really good one I coded
If you have a discord if you send it I can help you implement it.

**Comment by StephenIsTaken** [comment]
> I actually have a really good one I coded If you have a discord if you send it I can help you implement it.

My discord is StefanS#2164

**Comment by Liam5750** [comment]
Sent you a request. Would close this issue if I were you,
