### ISSUE TITLE
my resolver is retarded and making me retarded

### ISSUE THREAD

**Issue by Liam5750** [notgoodusename/OsirisAndExtra#492]
```Vector calcAngle(Vector source, Vector entityPos) {
	Vector delta = {};
	delta.x = source.x - entityPos.x;
	delta.y = source.y - entityPos.y;
	delta.z = source.z - entityPos.z;
	Vector angles = {};
	Vector viewangles = command->viewangles;
	Vector viewangles = command->viewangles;
	Vector viewangles = command->viewangles;
	Vector viewangles = command->viewangles;
	Vector viewangles = command->viewangles;
	angles.x = Helpers::rad2deg(atan(delta.z / hypot(delta.x, delta.y))) - viewangles.x;
	angles.y = Helpers::rad2deg(atan(delta.y / delta.x)) - viewangles.y;
	angles.z = 0;
	if (delta.x >= 0.f)
		angles.y += 180;

	return angles;
}
```
![image](https://user-images.githubusercontent.com/74884194/214942960-6241bad4-39ea-445c-b152-f6cdd69401d7.png)
idk what is up. Kinda why I quit using this repo in the first place. If I could get these dumb command was nullptr things to go away life would be so amazing.

**Comment by notgoodusename** [comment]
You forgot to call Resolver::commandGrabber on createmove

**Comment by Liam5750** [comment]
ok so first I know this image is cursed. I removed all of them but 1(why is there 5) and used UserCmd* cmd to change command to cmd and it's working now

**Comment by Liam5750** [comment]
> You forgot to call Resolver::commandGrabber on createmove

also thanks
