### ISSUE TITLE
Nothing changed as changing value of entity->EyeAngle.z

### ISSUE THREAD

**Issue by M3351AN** [notgoodusename/OsirisAndExtra#493]
I tried to make a roll brute force function,but I am struggled in changing enemies animations’ roll angle.For pitch and yaw, I can just set it a float and it works well.but as I change eyeangle.z,seems nothing happend but only weapons on enemies’ body turned around y axis(also tried offset m_angeyeangle +0x8, it is same)

**Comment by M3351AN** [comment]
> 

thx, i will try later

**Comment by froggisfriend** [comment]
you have to do your resolver in eye angles hook if you want to do that

and your other resolver should be in resolver for desync: and set animstate footyaw to correct ones and make sure you  set resolver to true in resolver.cop

**Comment by Liam5750** [comment]
> you have to do your resolver in eye angles hook if you want to do that
> 
> 
> 
> and your other resolver should be in resolver for desync: and set animstate footyaw to correct ones and make sure you  set resolver to true in resolver.cop

You have 0 idea about what this guy is talking about and neither does JannesBonk. You gotta hook ur epiK h@ck$ in da fuggin thingy and uhm like yeah idfk.

**Comment by Wolfyyta** [comment]
'resolve in eye angles hook' bro 💀
