### ISSUE TITLE
Crash Issues.

### ISSUE THREAD

**Issue by 1337Proxy1337** [notgoodusename/OsirisAndExtra#50]
if i try to join another match after i go rage last match my game insta crashes after the map loads.
The only way to fix the problem is to unhook after the rage game and rehook.

Injector: CSGHOST V4.3.1

**Comment by techzin** [comment]
try debug

**Comment by 1337Proxy1337** [comment]
> try debug

no errors and insta crash. i tried some stuff and realized it only crashes if i don't reinject after leaving a game and trying to join another.

**Comment by notgoodusename** [comment]
send your config

**Comment by 1337Proxy1337** [comment]
[HvH.txt](https://github.com/notgoodusename/OsirisAndExtra/files/8109691/HvH.txt)

changed it to .txt so i can upload it.

**Comment by notgoodusename** [comment]
I havent been able to replicate the crash, so idk how to fix it

**Comment by techzin** [comment]
do you have vcruntime x86 and x64?
