### ISSUE TITLE
Rage bot analysis

### ISSUE THREAD

**Issue by DNTtianci666** [notgoodusename/OsirisAndExtra#503]
The Rage robot resolution seems to be broken. I tried to use the Rage bot these days, but his empty gun is much more serious than before (often even ordinary players can't hit it). I used SSG 08 to adjust the accuracy to 80, which is still very bad. It may be that the resolution system is too old and needs to be updated

**Comment by Liam5750** [comment]
What the??? Anyways it's 100% a **YOU** issue. Not broken for anyone else.

**Comment by gr1ndy** [comment]
> It may be that the resolution system is too old and needs to be updated

the source is here, you can grab it and improve it at any time.
