### ISSUE TITLE
[REQUEST] Aim at backtrack feature

### ISSUE THREAD

**Issue by wirekuro** [notgoodusename/OsirisAndExtra#514]
as above
make aimbot aim at last backtrack tick.

**Comment by wirekuro** [comment]
> cuz u wanna paste that into ur? nah

Dude lmao im requesting a feature at the main project what do u complain about?

**Comment by Xsintashi** [comment]
ragebot already backtracks so idk how it should look with legit

**Comment by Wolfyyta** [comment]
ima explain it for ya, u want to add it learn how to code:
you need to find the closest backtrack tick to the cursor, once you find one make sure it is still active (backtrack doesnt always run at the same ticks) and bam you got it, to make a chams on it to see if it works save its matrix and do the chams in DME (replace original matrix with ur matrix from there)
