### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by StephenIsTaken** [notgoodusename/OsirisAndExtra#517]
Hi, I am very new to imgui and I really wanted to try and paste this [GUI](https://yougame.biz/threads/274346/) . If you think you can help me please add me on discord StefanS#2614. Also if pls dont be mean

**Comment by Liam5750** [comment]
LLLlLlLlLLLL

**Comment by StephenIsTaken** [comment]
> > Hi, I am very new to imgui and I really wanted to try and paste this [GUI](https://yougame.biz/threads/274346/) . If you think you can help me please add me on discord StefanS#2614. Also if pls dont be mean
> 
> omfg you want to paste a fucking open source gui? just learn how to use it. youtube is your best friend.

For example what video?

**Comment by JukoiDev** [comment]
for example learncpp.com and look at the structure of osiris' imgui/sdk

**Comment by JukoiDev** [comment]
and don't forget to hook
