### ISSUE TITLE
Some feature causes untrusted ban

### ISSUE THREAD

**Issue by dapaster** [notgoodusename/OsirisAndExtra#558]
I haven't played csgo for a moment , and just now when i load my old rage cfg i've got instant ban (competitive & casual)

already tried it at multiple account and the result is same.

may i know which feature cause this? did i miss anything about this cheat ?

My legit cfg seems fine, only got instant ban when loading the rage cfg

and im using the latest version

**Comment by dapaster** [comment]
> 

thanks for the info

**Comment by dapaster** [comment]
> > I haven't played csgo for a moment , and just now when i load my old rage cfg i've got instant ban (competitive & casual)
> > already tried it at multiple account and the result is same.
> > may i know which feature cause this? did i miss anything about this cheat ?
> > My legit cfg seems fine, only got instant ban when loading the rage cfg
> > and im using the latest version
> 
> features such as : glow, radar hack are detected, silent is also snappy and u may need to reduce aim step, also fun fact anti aim is detected now ( even legit aa somehow, i was cheating in prime with legit aa and started to get cheaters, with iniuria ). also i dont recommend to use rage at all since its very detected

you were right, after i toggled Desync i got kick by the game and then untrusted ban

**Comment by gr1ndy** [comment]
> 

are u albert einstein by any chance?

**Comment by mkot2** [comment]
> > I haven't played csgo for a moment , and just now when i load my old rage cfg i've got instant ban (competitive & casual)
> > already tried it at multiple account and the result is same.
> > may i know which feature cause this? did i miss anything about this cheat ?
> > My legit cfg seems fine, only got instant ban when loading the rage cfg
> > and im using the latest version
> 
> features such as : glow, radar hack are detected, silent is also snappy and u may need to reduce aim step, also fun fact anti aim is detected now ( even legit aa somehow, i was cheating in prime with legit aa and started to get cheaters, with iniuria ). also i dont recommend to use rage at all since its very detected

anything except AA is not being banned
