### ISSUE TITLE
hitchance problem, optimization, bad code

### ISSUE THREAD

**Issue by exfuturesolutions** [notgoodusename/OsirisAndExtra#560]
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/AimbotFunctions.cpp#LL559C8-L559C8
we haven't check many hitboxes it lowers our optimization and so unuseful, cuz we check if we have chance to hit certain hitbox for certain damage

**Comment by notgoodusename** [comment]
Explain yourself better
also if you mean that the for loop is unnecessary, it isn't, the reason i check for every hitbox is because the function needs to check a certain hitbox
this is because the function creates a "oval" (based on the position, size and rotation of the hitbox) and compares if the given direction hits said "oval"

**Comment by exfuturesolutions** [comment]
why do u check each hitbox for intersect if u want to hit certain hit box, chosen by ur hitscan?

**Comment by exfuturesolutions** [comment]
why not just
bool bIntersectedCertainHbox = hitbox_intersection(certain_hbox, matrix)
if(!bIntersectedCertainHbox)
    continue
else
     hits++
cuz u dont need to check another hitboxes for intersect u need certain bro, arent i right?

**Comment by exfuturesolutions** [comment]
idk where this hitchance from but it's not proper to check up to (256 * hitboxes) intersections, it will slow the performance, also results will be damn not accurately cuz u check intersection for the whole enemy when need check only one intersected hitbox

**Comment by notgoodusename** [comment]
> idk where this hitchance from but it's not proper to check up to (256 * hitboxes) intersections, it will slow the performance, also results will be damn not accurately cuz u check intersection for the whole enemy when need check only one intersected hitbox

change the code and then see why it doesn't work, im not going to explain something that requires 1 google search
