### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by N0ppe** [notgoodusename/OsirisAndExtra#580]
Error LNK1120	1 unresolved externals C:\Users\myname\Desktop\OsirisAndExtra-main\OsirisAndExtra-main\Release\Osiris.dll	1	

LNK2001	unresolved external symbol "void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (?_Raise_handler@std@@3P6AXABVexception@stdext@@@ZA::<!std>) C:\Users\myname\Desktop\OsirisAndExtra-main\OsirisAndExtra-main\Osiris\std.ixx.obj	1	

Hopefully someone can help me with this 💀

**Comment by notgoodusename** [comment]
What versionn of vs are you using? have tried [this pr](https://github.com/notgoodusename/OsirisAndExtra/pull/581)?

**Comment by N0ppe** [comment]
I got it fixed with the fix you linked for me. Thanks!

**Comment by N0ppe** [comment]
Thanks for help.
