### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by nvx0** [notgoodusename/OsirisAndExtra#6]
it is crashing my game

**Comment by notgoodusename** [comment]
Describe when does it happen

**Comment by nvx0** [comment]
ExtremeInjector 
Manual Map

**Comment by notgoodusename** [comment]
Try using [CSGhost injector](https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html)

**Comment by Ativ3k** [comment]
If u use RTSS or MSI Afterburner disable it.

I use RTSS & MSI and it crash game when Osiris Menu is opened.
