### ISSUE TITLE
How to support this project?

### ISSUE THREAD

**Issue by techzin** [notgoodusename/OsirisAndExtra#65]
Hello, I've been really enjoying playing on the weekends with this Open Source project, I would like to know how to financially support this project, do you have any donate links? or patreon?

**Comment by notgoodusename** [comment]
I dont think there is, Im underage at the moment
If i find a way to get donations i will link it on this repo

**Comment by techzin** [comment]
Do you have discord?

**Comment by notgoodusename** [comment]
um yea

**Comment by notgoodusename** [comment]
seka#5706
