### ISSUE TITLE
Can you please also include the compile or ddl version of the source

### ISSUE THREAD

**Issue by hamzah-sajid-code** [notgoodusename/OsirisAndExtra#67]

**Comment by Metaphysical1** [comment]
what?

**Comment by Patrixsin** [comment]
he means he wants to built dll version of cheat and placed in releases section i guess

**Comment by BasicllyMaximqs** [comment]
really not that hard to build it yourself, vs2019 and v142 or newer and u should be literally able to just compile

**Comment by okwannabe** [comment]
here but i changed the menu a bit and is shit so .....
https://imgur.com/MeoLOod

https://easyupload.io/xukoek
