### ISSUE TITLE
Untrusted

### ISSUE THREAD

**Issue by PrototypeError** [notgoodusename/OsirisAndExtra#68]
Hi I use Vac Bypass but when play matchmaking with rage after some time i just get untrusted. Can i just ask what is adblock in misc for?

**Comment by PrototypeError** [comment]
Can i just ask you how to use aimstep? Like im not new into programming i just never had problems to this day with untrusted bans. Also what is adblock in misc? Thank you very much for answer.

**Comment by Patrixsin** [comment]
For ADBlock - it blocks all screen ads on community servers I guess - here is example https://www.youtube.com/watch?v=JedNuB2GcWo

**Comment by propane** [comment]
> Can i just ask you how to use aimstep? Like im not new into programming i just never had problems to this day with untrusted bans. Also what is adblock in misc? Thank you very much for answer.

clamp the aimbot viewangles change per tick
