### ISSUE TITLE
Crashing after one or more matches played for no reason

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#72]
Injector i use and also tried : MadInjector Custom load library (works the best cause it allows me to play more matches, most of the times only 3), CSGHOST v4.3.1 (same), sazinjector(only 2 rounds in and crash). What xan i do to fix?

**Comment by notgoodusename** [comment]
I have been unable to reproduce this issue, so I ask of you to debug the dll while playing and to post some screenshots here

**Comment by JannesBonk** [comment]
> I have been unable to reproduce this issue, so I ask of you to debug the dll while playing and to post some screenshots here

how can i debug?
when i attach it dosent show the menu
