### ISSUE TITLE
Doubletap

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#79]

**Comment by thezelax** [comment]
how can there be a issue with a non existing feature

**Comment by Patrixsin** [comment]
he's just requesting those stuff

**Comment by thezelax** [comment]
> he's just requesting those stuff

tickbase manipulation is already in the TODO if you guys can check

**Comment by thezelax** [comment]
https://github.com/notgoodusename/OsirisAndExtra/projects/1
