### ISSUE TITLE
Flash Reduction Is not working.

### ISSUE THREAD

**Issue by diekunstderfuge** [notgoodusename/OsirisAndExtra#8]
Flash Reduction Is not working.

**Comment by notgoodusename** [comment]
This was already fixed ([27bc9d1](https://github.com/notgoodusename/OsirisAndExtra/commit/27bc9d13aa3044f74e6d40fdc1093d7e1cc0466c)) and heres a [video](https://streamable.com/i8ia66) of it working fine

**Comment by BuddyBoi** [comment]
If you can fix flash then you don’t know the basics

**Comment by notgoodusename** [comment]
> If you can fix flash then you don’t know the basics

What does this mean????

**Comment by diekunstderfuge** [comment]
It is working! Thanks!
