### ISSUE TITLE
Bullet tracers

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#81]
idk why but the bullet tracers are broken, when i shoot or the rage bot shoots, it should show only one tracer, but no it shows 2 or 3 or 4. The single time this didnt happend is when i didnt wallbang

**Comment by notgoodusename** [comment]
Im aware and im working on it

**Comment by JannesBonk** [comment]
Thank you!

**Comment by JannesBonk** [comment]
> Im aware and im working on it

can u please add a flags section in esp? like fake duck or how much money they got and something like that?

**Comment by notgoodusename** [comment]
Fixed
