### ISSUE TITLE
suggestion: Spray assist

### ISSUE THREAD

**Issue by Exploriant** [notgoodusename/OsirisAndExtra#83]

**Comment by propane** [comment]
the aimbot has "Spray assist" which you mean RCS (Recoil Control System). Its just not standalone or configurable X and Y, it just does recoil amount based on your aimbot smoothing and fov. hope this helps.

**Comment by Exploriant** [comment]
> the aimbot has "Spray assist" which you mean RCS (Recoil Control System). Its just not standalone or configurable X and Y, it just does recoil amount based on your aimbot smoothing and fov. hope this helps.

How do I turn it on

**Comment by propane** [comment]
> > the aimbot has "Spray assist" which you mean RCS (Recoil Control System). Its just not standalone or configurable X and Y, it just does recoil amount based on your aimbot smoothing and fov. hope this helps.
> 
> How do I turn it on

Like i said "its not standalone" its not a feature you turn on in the aimbot, nor does it do recoil when you are not aimbotting an enemy.  The aimbot does recoil control based on the smoothness / speed you have set on your aimbot, and the angle that the enemy is relative to you.

**Comment by Exploriant** [comment]
> > > the aimbot has "Spray assist" which you mean RCS (Recoil Control System). Its just not standalone or configurable X and Y, it just does recoil amount based on your aimbot smoothing and fov. hope this helps.
> > 
> > 
> > How do I turn it on
> 
> Like i said "its not standalone" its not a feature you turn on in the aimbot, nor does it do recoil when you are not aimbotting an enemy. The aimbot does recoil control based on the smoothness / speed you have set on your aimbot, and the angle that the enemy is relative to you.

Oh so it has something with max angle delta to do? If not I think i understand
