### ISSUE TITLE
Jitter Yaw

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#84]

**Comment by JannesBonk** [comment]
go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings

**Comment by Rrhyast** [comment]
> go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings

since its limited to 60 and being static doesn't help much.

**Comment by JannesBonk** [comment]
> > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> 
> since its limited to 60 and being static doesn't help much. 

did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5

**Comment by JannesBonk** [comment]
> > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > 
> > > 
> > > since its limited to 60 and being static doesn't help much.
> > 
> > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> 
> that's why it sucks.

for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)

**Comment by Rrhyast** [comment]
> > > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > > 
> > > > 
> > > > since its limited to 60 and being static doesn't help much.
> > > 
> > > 
> > > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> > 
> > 
> > that's why it sucks.
> 
> for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)

XD how

**Comment by JannesBonk** [comment]
> > > > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > > > 
> > > > > 
> > > > > since its limited to 60 and being static doesn't help much.
> > > > 
> > > > 
> > > > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> > > 
> > > 
> > > that's why it sucks.
> > 
> > for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)
> 
> XD how 
**magic**

**Comment by Rrhyast** [comment]
> > > > > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > > > > 
> > > > > > 
> > > > > > since its limited to 60 and being static doesn't help much.
> > > > > 
> > > > > 
> > > > > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> > > > 
> > > > 
> > > > that's why it sucks.
> > > 
> > > 
> > > for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)
> > 
> > 
> > XD how
> > **magic**
![csgo_ZUd9MvPe3o](https://user-images.githubusercontent.com/62977195/164445076-c0bf4396-70e9-4a3f-950e-a92cdb7e634f.jpg) 
my aa sucks but i tap nl users

**Comment by JannesBonk** [comment]
> > > > > > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > > > > > 
> > > > > > > 
> > > > > > > since its limited to 60 and being static doesn't help much.
> > > > > > 
> > > > > > 
> > > > > > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> > > > > 
> > > > > 
> > > > > that's why it sucks.
> > > > 
> > > > 
> > > > for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)
> > > 
> > > 
> > > XD how
> > > **magic**
> ![csgo_ZUd9MvPe3o](https://user-images.githubusercontent.com/62977195/164445076-c0bf4396-70e9-4a3f-950e-a92cdb7e634f.jpg) 
> my aa sucks but i tap nl users
> 
> 

what if its a otc v3 guy with a js?

**Comment by Rrhyast** [comment]
> > > > > > > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > > > > > > 
> > > > > > > > 
> > > > > > > > since its limited to 60 and being static doesn't help much.
> > > > > > > 
> > > > > > > 
> > > > > > > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> > > > > > 
> > > > > > 
> > > > > > that's why it sucks.
> > > > > 
> > > > > 
> > > > > for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)
> > > > 
> > > > 
> > > > XD how
> > > > **magic**
> > > > ![csgo_ZUd9MvPe3o](https://user-images.githubusercontent.com/62977195/164445076-c0bf4396-70e9-4a3f-950e-a92cdb7e634f.jpg)
> > > > my aa sucks but i tap nl users
> 
> what if its a otc v3 guy with a js?

otc is dead 1000%

**Comment by JannesBonk** [comment]
> > > > > > > > > > go to fake angle tab, select from the first drop down menu litter and on the second one select normal, then mess with the settings to your likings
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > since its limited to 60 and being static doesn't help much.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > did u use fake-lag? Because, the fake angle feature dosen't work without fake lag, but for me, it's going nutz with these settings amd fake lag set to 5
> > > > > > > 
> > > > > > > 
> > > > > > > that's why it sucks.
> > > > > > 
> > > > > > 
> > > > > > for me, it's working very good, i even made unhittable anti-aim for hvh (works best against otc, lw v3, rawetrip, and nixware users)
> > > > > 
> > > > > 
> > > > > XD how
> > > > > **magic**
> > > > > ![csgo_ZUd9MvPe3o](https://user-images.githubusercontent.com/62977195/164445076-c0bf4396-70e9-4a3f-950e-a92cdb7e634f.jpg)
> > > > > my aa sucks but i tap nl users
> > 
> > what if its a otc v3 guy with a js?
> 
> otc is dead 1000% 

its still working but its very 🤮

**Comment by notgoodusename** [comment]
> that's why it sucks.

fakelag is always necessary for fake angles to work, it just a fact, you cant have fake angles without fakelag

**Comment by roscagio** [comment]
shouldn' t activating desync implicitly activate fake lag too?

**Comment by notgoodusename** [comment]
> shouldn' t activating desync implicitly activate fake lag too?

[sure](https://github.com/notgoodusename/OsirisAndExtra/commit/103f0f20b757b2907313dc8016163a1ffc90386f)
