### ISSUE TITLE
setting max angle delta causes issues with antiaim and desync

### ISSUE THREAD

**Issue by Metaphysical1** [notgoodusename/OsirisAndExtra#86]
as the title says, I need to use antiaim in MM with low view angle delta so can't get instant untrusted
for example if I set max angle delta to 39 and downward pitch AA, player shoots ground

**Comment by voidzer0-development** [comment]
It will clamp the aimbot from the look position which is down

**Comment by Metaphysical1** [comment]
> It will clamp the aimbot from the look position which is down

yes that's how it's working right now, but this makes AA unusable in MM and casual matches
Many P2C works in casual matches, so they must be using aimstep, right?

**Comment by propane** [comment]
> > It will clamp the aimbot from the look position which is down
> 
> yes that's how it's working right now, but this makes AA unusable in MM and casual matches Many P2C works in casual matches, so they must be using aimstep, right?

I simply removed the createMove hook maxAngleDelta clamping all the viewangles, and then kept the maxAngleDelta angle clamping in the aimbot, works great for me.

**Comment by Metaphysical1** [comment]
> 
> I simply removed the createMove hook maxAngleDelta clamping all the viewangles, and then kept the maxAngleDelta angle clamping in the aimbot, works great for me. (the maxAngleDelta clamp in the aimbot is same as aimstep)

thanks, I tried commenting these 2 lines in createmove
https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hooks.cpp#L284-L285
it worked, but I still getting kicked from casual matches, I looked into other cheats source leak and they are doing aimstepping inc antiaim code

**Comment by voidzer0-development** [comment]
> > > It will clamp the aimbot from the look position which is down
> > 
> > 
> > yes that's how it's working right now, but this makes AA unusable in MM and casual matches Many P2C works in casual matches, so they must be using aimstep, right?
> 
> I simply removed the createMove hook maxAngleDelta clamping all the viewangles, and then kept the maxAngleDelta angle clamping in the aimbot, works great for me. (the maxAngleDelta clamp in the aimbot is same as aimstep)

You will keep getting kicked when using down antiaim, what you need to do is save a state between two calls of the createmove hook.

**Comment by voidzer0-development** [comment]
> > > It will clamp the aimbot from the look position which is down
> > 
> > 
> > yes that's how it's working right now, but this makes AA unusable in MM and casual matches Many P2C works in casual matches, so they must be using aimstep, right?
> 
> I simply removed the createMove hook maxAngleDelta clamping all the viewangles, and then kept the maxAngleDelta angle clamping in the aimbot, works great for me. (the maxAngleDelta clamp in the aimbot is same as aimstep)

Correct, but just clamping the delta is not the same as aimstep, as the name suggests you go step by step every createmove call so you need to prevent it from being reset back before having aquired the target point.
