### ISSUE TITLE
Why a mix of stdcall and fastcall?

### ISSUE THREAD

**Issue by BuddyBoi** [notgoodusename/OsirisAndExtra#9]
Fastcall is slower so do certain hooks need to run slower?

I’m experienced but new to internals. 
thanks in advance 

Edit: also the grenade prediction accounts for players which cheats rarely do, but the adjustment for players isn’t calculated right it calculates them as a wall

**Comment by notgoodusename** [comment]
The hooks having fastcall has nothing to do with running slow or fast, its has to do with how the compiler sets the calls to functions, so when hooking them you have to set it to the same call to get the same registers

And about grenade prediction I dont really bother to fix it

**Comment by BuddyBoi** [comment]
Thanks for the response
