### ISSUE TITLE
Crashing when glow is on and entering a new match

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#94]
I was playing with my legit config which has only chams and aimbot (fov 0.98) and after that i wanted to play with my friend hvh, so i loaded my hvh config which has glow and makes the visuals look super sick and csgo crashed. After that i tried again and the same shit happend. I removed the glow from the config file and it stopped crashing.

**Comment by notgoodusename** [comment]
Can you enable glow in game?

**Comment by JannesBonk** [comment]
> Can you enable glow in game?

i can enable the glow in game but if i rejoin or join another match its crashing

**Comment by gr1ndy** [comment]
for me it just crashes after i join another match

**Comment by JannesBonk** [comment]
> for me it just crashes after i join another match

same

**Comment by propane** [comment]
> Can you enable glow in game?

The glow is working, but if it is on when player joins a match it crashes.. may have been fixed in your latest push where you reset Glow objects on level shutdown... will reply after checking

**Comment by propane** [comment]
> > Can you enable glow in game?
> 
> The glow is working, but if it is on when player joins a match it crashes.. may have been fixed in your latest push where you reset Glow objects on level shutdown... will reply after checking

crashing on level shutdown now if glow is on

**Comment by notgoodusename** [comment]
> crashing on level shutdown now if glow is on

Can you debug?

**Comment by propane** [comment]
> > crashing on level shutdown now if glow is on
> 
> Can you debug?

I will try to, my visual studio sometimes refuses to give me names of functions or callstack it crashes from when im debugging.
