### ISSUE TITLE
[ Suggestion ] Custom colored grenade prediciton

### ISSUE THREAD

**Issue by JannesBonk** [notgoodusename/OsirisAndExtra#98]
Just like in otc v3 or moonlight, i think we can have custom colored grenade prediction instead of the default one

**Comment by JukoiDev** [comment]
It wouldn't be so hard cuz the current nade predict is so well written you just have to add config and replace the current color values with these from config. Imma do it when i will have time.

**Comment by Navoichyk** [comment]
> > It wouldn't be so hard cuz the current nade predict is so well written you just have to add config and replace the current color values with these from config. Imma do it when i will have time.
> 
> i already did it in my paste lol

Make a pr

**Comment by Navoichyk** [comment]
> > > > It wouldn't be so hard cuz the current nade predict is so well written you just have to add config and replace the current color values with these from config. Imma do it when i will have time.
> > > 
> > > 
> > > i already did it in my paste lol
> > 
> > 
> > Make a pr
> 
> i am kn vacation

Oh okay, well when you come back then?
